// ConnectionTree_Events.cpp — tree event handlers and the per-node context menu,
// split out of ConnectionTree.cpp per the ≤1000-line charter (docs/CHARTER.md).
// The method bodies below are the exact originals; behavior is unchanged. The
// menu-only helpers (ColorSwatch, kConnColors, NewTableTemplate) are kept
// file-local here since nothing else uses them.
#include "ui/ConnectionTree.h"
#include "ui/ConnectionTreeInternal.h"

#include <wx/wx.h>
#include <wx/colordlg.h>
#include <wx/dcmemory.h>
#include <wx/treectrl.h>
#include <wx/generic/treectlg.h>

#include "ui/CenteredDialog.h"
#include "ui/I18n.h"
#include "ui/IconFactory.h"
#include "ui/ObjectTemplates.h"
#include "ui/RoutineExecDialog.h"
#include "ui/SqlErrorDialog.h"
#include "ui/Theme.h"

namespace ui {

namespace {

// A solid-colour square for a "设置颜色" menu item's bitmap.
wxBitmap ColorSwatch(const wxColour& c, int size = 14)
{
    wxBitmap bm(size, size);
    wxMemoryDC dc(bm);
    dc.SetBackground(wxBrush(c));
    dc.Clear();
    dc.SetPen(wxPen(wxColour(0, 0, 0, 40)));   // faint outline so light swatches read
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRectangle(0, 0, size, size);
    dc.SelectObject(wxNullBitmap);
    return bm;
}

// Connection colour presets — label + "#RRGGBB". Kept small and legible.
struct ConnColor { const wchar_t* name; const wchar_t* hex; };
constexpr ConnColor kConnColors[] = {
    { L"红色", L"#E5484D" }, { L"橙色", L"#F76B15" }, { L"黄色", L"#FFB224" },
    { L"绿色", L"#30A46C" }, { L"蓝色", L"#2C7BE5" }, { L"紫色", L"#8E4EC6" },
    { L"灰色", L"#8B8D98" },
};

// A starter CREATE TABLE statement for the dialect — "新建表" opens a query
// prefilled with this so the user edits a real, idiomatic skeleton (auto-inc /
// identity / serial differ per engine) instead of a blank page.
inline wxString NewTableTemplate(db::Dialect d)
{
    switch (d) {
    case db::Dialect::Postgres:
        return L"CREATE TABLE new_table (\n"
               L"    id          SERIAL PRIMARY KEY,\n"
               L"    name        VARCHAR(255) NOT NULL,\n"
               L"    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
               L");\n";
    case db::Dialect::Sqlite:
        return L"CREATE TABLE new_table (\n"
               L"    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
               L"    name        TEXT NOT NULL,\n"
               L"    created_at  TEXT DEFAULT (datetime('now'))\n"
               L");\n";
    case db::Dialect::SqlServer:
        return L"CREATE TABLE new_table (\n"
               L"    id          INT IDENTITY(1,1) PRIMARY KEY,\n"
               L"    name        NVARCHAR(255) NOT NULL,\n"
               L"    created_at  DATETIME DEFAULT GETDATE()\n"
               L");\n";
    case db::Dialect::Oracle:
        // 12c+ IDENTITY column; VARCHAR2 is Oracle's canonical string type. DM8
        // accepts this verbatim (Oracle-compatible DDL).
        return L"CREATE TABLE new_table (\n"
               L"    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
               L"    name        VARCHAR2(255) NOT NULL,\n"
               L"    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
               L");\n";
    case db::Dialect::MySQL:
    default:
        return L"CREATE TABLE new_table (\n"
               L"    id          INT AUTO_INCREMENT PRIMARY KEY,\n"
               L"    name        VARCHAR(255) NOT NULL,\n"
               L"    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
               L") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n";
    }
}

} // namespace

// ---------------------------------------------------------------------------
void ConnectionTree::OnActivated(wxTreeEvent& ev)
{
    auto* data = dynamic_cast<NodeData*>(tree_->GetItemData(ev.GetItem()));
    if (!data) return;

    switch (data->kind) {
    case NodeData::Group:
        // Double-click a 分组 = the explicit "open it" gesture: show its contents
        // AND pull the tab to the front, mirroring what a database node does.
        tree_->Toggle(ev.GetItem());
        NotifyGroupSelected(data, /*focus*/ true);
        break;
    case NodeData::Connection:
        if (!data->entry->IsConnected()) {
            ConnectEntry(data->entry);   // shows the overview on success (inside)
        } else {
            tree_->Toggle(ev.GetItem());
            if (hooks_.showOverview) hooks_.showOverview(data->entry);
        }
        break;
    case NodeData::Database:
        active_ = data->entry;
        data->entry->currentDb = data->db;
        LoadCategories(ev.GetItem(), data->entry, data->db);
        tree_->Toggle(ev.GetItem());
        // 双击库 = 明确"打开"手势 → 更新表列表内容并把标签切到前面。
        if (hooks_.showDatabase) hooks_.showDatabase(data->entry, data->db, /*focus*/ true);
        break;
    case NodeData::CategoryNode:
        active_ = data->entry;
        data->entry->currentDb = data->db;
        LoadCategoryMembers(ev.GetItem());
        tree_->Toggle(ev.GetItem());
        break;
    case NodeData::Table:
        active_ = data->entry;
        data->entry->currentDb = data->db;
        // Routine leaves (函数/存储过程) open the 修改 object editor on double-click;
        // tables and views open the data grid (views browse like tables).
        if (data->cat == Category::Functions || data->cat == Category::Procedures) {
            const ObjectKind k = (data->cat == Category::Procedures)
                                     ? ObjectKind::Procedure : ObjectKind::Function;
            if (data->entry->conn &&
                ObjectCreateSupported(k, data->entry->conn->GetDialect()))
                ModifyObject(data->entry, data->db, data->table, k);
        } else {
            hooks_.openTable(data->entry, data->db, data->table);
        }
        break;
    }
}

// Lazy load on expand — so opening a node via the chevron (single click) loads
// its members too, not only via double-click activation. Both call the same
// loaders, which no-op when the node is already loaded, so the two paths never
// double-fetch. Without this, a chevron-expanded node stays stuck on its
// icon-less "加载中…" placeholder.
void ConnectionTree::OnItemExpanding(wxTreeEvent& ev)
{
    auto* data = dynamic_cast<NodeData*>(tree_->GetItemData(ev.GetItem()));
    if (!data) { ev.Skip(); return; }

    switch (data->kind) {
    case NodeData::Connection:
        // Expanding a not-yet-connected connection connects it and loads its
        // database list. Deferred with CallAfter so we don't re-enter the tree's
        // expand machinery (LoadDatabases itself calls Expand) from inside this
        // EXPANDING event — which is fragile in the generic tree.
        if (!data->entry->IsConnected()) {
            ConnEntry* en = data->entry;
            tree_->CallAfter([this, en] { if (!en->IsConnected()) ConnectEntry(en); });
        }
        break;
    case NodeData::Database:
        active_ = data->entry;
        data->entry->currentDb = data->db;
        LoadCategories(ev.GetItem(), data->entry, data->db);
        // Expanding via the chevron is a pure "browse structure" gesture: refresh
        // the 表列表 tab's content but DON'T steal the user's current tab. A single
        // click on the db node (OnSelChanged) or a double-click (OnActivated) is
        // what brings the overview to the front.
        if (hooks_.showDatabase) hooks_.showDatabase(data->entry, data->db, /*focus*/ false);
        break;
    case NodeData::CategoryNode:
        active_ = data->entry;
        data->entry->currentDb = data->db;
        LoadCategoryMembers(ev.GetItem());
        break;
    default:
        break;
    }
    ev.Skip();   // let the expansion proceed
}

// Single-click "follow": clicking a database node (expanded or NOT) shows its
// table list up front. GetTableList queries information_schema by the specific db
// (no USE / current-db dependency), so a still-collapsed database loads its tables
// just fine. ShowDatabaseOverview no-ops (no reload) when it's already the shown
// db, so re-clicking the same db stays cheap.
//
// This path only fires when the user is actively engaging the tree (a mouse click,
// or arrow keys WHILE the tree holds focus) — never while typing in the SQL editor,
// where keystrokes move the editor caret and don't touch tree selection. So pulling
// the 表列表 tab to the front here can't interrupt SQL writing; it just fulfils the
// "click a db → see its tables" gesture the user asked for.
void ConnectionTree::OnSelChanged(wxTreeEvent& ev)
{
    auto* data = dynamic_cast<NodeData*>(tree_->GetItemData(ev.GetItem()));
    // 分组 folder → show its contents in the fixed tab. Same "follow the click"
    // rule as a database node below: update the content, never steal focus.
    if (data && data->kind == NodeData::Group) {
        NotifyGroupSelected(data, /*focus*/ false);
        ev.Skip();
        return;
    }
    // 选中"表"节点:同步当前表(供"查看→表设计"菜单用),不打开任何标签。
    if (data && data->kind == NodeData::Table) {
        active_ = data->entry;
        data->entry->currentDb = data->db;
        if (hooks_.selectTable) hooks_.selectTable(data->entry, data->db, data->table);
        ev.Skip();
        return;
    }
    // 选中"数据库"节点，或该库的"表"分类节点，都把共享"表列表"标签切到这个库。
    // (去掉"必须已展开"的旧限制:重复选中同库时 ShowDatabaseOverview 会 no-op,很便宜。)
    const bool isDb    = data && data->kind == NodeData::Database;
    const bool isTables = data && data->kind == NodeData::CategoryNode
                               && data->cat == Category::Tables;
    if (!data || (!isDb && !isTables)) {
        ev.Skip();
        return;
    }
    // 只有"已打开(已展开)"的数据库才在单击时加载表:折叠(=未打开)的库单击不加载,
    // 右侧表列表保持空;要看它的表得先"打开"(双击/展开)。"表"分类节点只有在其库已
    // 展开时才可见,故它天然已满足"已打开",无需再判。
    if (isDb && !tree_->IsExpanded(ev.GetItem())) {
        // 单击"未打开"的库:不加载,并清空右侧表列表(从已打开的库切到未打开的库,
        // 表信息也要清掉)。
        if (hooks_.clearTables) hooks_.clearTables(data->entry, data->db, /*force*/ true);
        ev.Skip();
        return;
    }
    active_ = data->entry;
    data->entry->currentDb = data->db;
    // 单击一个"已打开"的库(或其"表"分类节点)只更新表列表内容,不抢焦点(用户可能正在
    // 别的标签,不该被拽走);"打开"动作(双击/展开)自身走 focus=true 切到前面。
    if (hooks_.showDatabase) hooks_.showDatabase(data->entry, data->db, /*focus*/ false);
    ev.Skip();
}

void ConnectionTree::OnRightClick(wxTreeEvent& ev)
{
    const wxTreeItemId item = ev.GetItem();
    if (!item.IsOk()) return;
    tree_->SelectItem(item);
    ShowNodeContextMenu(item);
}

// F2 on a selected leaf → rename it. Leaves share NodeData::Table but represent
// different objects (data->cat): a real table uses RENAME/ALTER TABLE (RenameTable),
// while a view / function / procedure must NOT (MySQL's RENAME TABLE rejects them) —
// they route to RenameObject, which picks the right per-dialect strategy.
void ConnectionTree::OnTreeKey(wxTreeEvent& ev)
{
    if (ev.GetKeyCode() == WXK_F2) {
        const wxTreeItemId item = ev.GetItem().IsOk() ? ev.GetItem() : tree_->GetSelection();
        auto* data = item.IsOk() ? dynamic_cast<NodeData*>(tree_->GetItemData(item)) : nullptr;
        if (data && data->kind == NodeData::Table && data->entry) {
            switch (data->cat) {
            case Category::Views:
                RenameObject(data->entry, data->db, data->table, ObjectKind::View);
                break;
            case Category::Functions:
                RenameObject(data->entry, data->db, data->table, ObjectKind::Function);
                break;
            case Category::Procedures:
                RenameObject(data->entry, data->db, data->table, ObjectKind::Procedure);
                break;
            default:   // Tables (and any other) → the table rename path, unchanged.
                RenameTable(data->entry, data->db, data->table);
                break;
            }
            RefreshTableCategory(item);
            return;
        }
    }
    ev.Skip();
}

void ConnectionTree::ShowNodeContextMenu(const wxTreeItemId& item)
{
    auto* data = dynamic_cast<NodeData*>(tree_->GetItemData(item));
    if (!data) return;
    ConnEntry* e = data->entry;

    wxMenu menu;
    auto add = [&](const wxString& label, std::function<void()> fn) {
        wxMenuItem* mi = menu.Append(wxID_ANY, label);
        menu.Bind(wxEVT_MENU, [fn](wxCommandEvent&) { fn(); }, mi->GetId());
    };
    // A greyed placeholder for a feature that isn't wired up yet — mirrors the
    // context-dependent greying in the reference design (sn_2.jpg).
    auto addOff = [&](const wxString& label) { menu.Append(wxID_ANY, label)->Enable(false); };

    // 分组 folders own their whole menu and share nothing with the object menus
    // below — which is also why this returns rather than falling through: every
    // arm after it dereferences `e`, and a CONNECTION group node deliberately
    // has none (it contains connections, see NodeData in ConnectionTreeInternal.h).
    if (data->kind == NodeData::Group) {
        AppendGroupMenu(menu, item, data);
        tree_->PopupMenu(&menu);
        return;
    }

    switch (data->kind) {
    case NodeData::Connection: {
        if (e->IsConnected()) {
            add(tr(L"断开连接"), [this, e] { DisconnectEntry(e); });
            add(tr(L"刷新"), [this, e] { LoadDatabases(e); });
        } else {
            add(tr(L"打开连接"), [this, e] { ConnectEntry(e); });
        }
        menu.AppendSeparator();
        add(tr(L"编辑连接"), [this, e] { EditConnection(e); });
        add(tr(L"复制连接"), [this, e] { DuplicateConnection(e); });
        // 设置颜色 ▶ — colour-code this connection's tree label
        {
            auto* sub = new wxMenu;
            for (const ConnColor& cc : kConnColors) {
                wxMenuItem* mi = sub->Append(wxID_ANY, tr(cc.name));
                mi->SetBitmap(ColorSwatch(wxColour(cc.hex)));
                const wxString hex = cc.hex;
                sub->Bind(wxEVT_MENU, [this, e, hex](wxCommandEvent&) {
                    SetConnColor(e, hex);
                }, mi->GetId());
            }
            sub->AppendSeparator();
            {
                wxMenuItem* mi = sub->Append(wxID_ANY, tr(L"自定义"));
                sub->Bind(wxEVT_MENU, [this, e](wxCommandEvent&) {
                    wxColour init = e->profile.color.IsEmpty()
                                        ? *wxWHITE : wxColour(e->profile.color);
                    wxColour picked = wxGetColourFromUser(dialogParent_, init,
                                                          tr(L"自定义颜色"));
                    if (picked.IsOk())
                        SetConnColor(e, picked.GetAsString(wxC2S_HTML_SYNTAX));
                }, mi->GetId());
            }
            {
                wxMenuItem* mi = sub->Append(wxID_ANY, tr(L"清除颜色"));
                mi->Enable(!e->profile.color.IsEmpty());
                sub->Bind(wxEVT_MENU, [this, e](wxCommandEvent&) {
                    SetConnColor(e, wxString());
                }, mi->GetId());
            }
            menu.AppendSubMenu(sub, tr(L"设置颜色"));
        }
        add(tr(L"删除连接"), [this, e] { DeleteConnection(e); });
        // 新建连接 ▶ — pick an engine to create another connection
        auto* sub = new wxMenu;
        for (const db::DbTypeInfo& info : db::AllDbTypes()) {
            wxMenuItem* mi = sub->Append(wxID_ANY, info.name);
            mi->SetBitmap(icons::DbBrand(info.type, 16));
            const db::DbType type = info.type;
            sub->Bind(wxEVT_MENU, [this, type](wxCommandEvent&) {
                OpenConnectionDialog(type);
            }, mi->GetId());
        }
        menu.AppendSubMenu(sub, tr(L"新建连接"));
        menu.AppendSeparator();
        {
            wxMenuItem* nd = menu.Append(wxID_ANY, tr(L"新建数据库"));
            if (e->IsConnected())
                menu.Bind(wxEVT_MENU, [this, e](wxCommandEvent&) { NewDatabase(e); }, nd->GetId());
            else
                nd->Enable(false);
        }
        add(tr(L"新建SQL"), [this, e] { active_ = e; hooks_.newQuery(e, e->currentDb); });
        break;
    }
    case NodeData::Database: {
        // Database nodes only exist under a live connection, so GetDialect() is
        // safe here. Capabilities gate which items light up per engine.
        const DbCaps caps = CapsFor(e->conn->GetDialect());

        // 打开/关闭数据库 — toggle on data->loaded, the tree's own "this database's
        // categories are loaded/expanded" flag. Open loads + expands; close
        // unloads + collapses (the faithful inverse, mirroring DisconnectEntry).
        if (data->loaded) {
            add(tr(L"关闭数据库"), [this, item, e, data] {
                // A category (Tables/Views/…) under this db may be loading on the
                // catWorker_ thread right now; DeleteChildren frees those nodes. Abort +
                // bump the generation FIRST so the worker's queued CallAfter is discarded
                // (its `gen != catGen_` guard) instead of dereferencing a freed tree node.
                // Every other structural delete already does this — this handler was the
                // sole omission and the resulting use-after-free was a real crash path.
                AbortCatWorker();
                data->loaded = false;
                tree_->DeleteChildren(item);
                tree_->Collapse(item);
                tree_->SetItemHasChildren(item, true);   // keep the chevron to re-open
                if (e->currentDb == data->db) e->currentDb.clear();
                // 关闭库 → 若右侧正显示这个库的表,清空表列表。
                if (hooks_.clearTables) hooks_.clearTables(e, data->db, /*force*/ false);
            });
        } else {
            add(tr(L"打开数据库"), [this, item, e, data] {
                active_ = e; e->currentDb = data->db;
                data->loaded = false; LoadCategories(item, e, data->db); tree_->Expand(item);
            });
        }
        menu.AppendSeparator();
        // 编辑数据库 — dialect-gated: only the MySQL family can ALTER a database.
        if (caps.editDatabase)
            add(tr(L"编辑数据库"), [this, e, data] { EditDatabase(e, data->db); });
        else
            addOff(tr(L"编辑数据库"));
        add(tr(L"新建数据库"), [this, e] { NewDatabase(e); });
        add(tr(L"删除数据库"), [this, e, data] { DeleteDatabase(e, data->db); });
        menu.AppendSeparator();
        add(tr(L"新建SQL"), [this, e, data] {
            active_ = e; e->currentDb = data->db; hooks_.newQuery(e, data->db);
        });
        menu.AppendSeparator();
        // 控制台 — for now an alias for a new query editor on this database.
        add(tr(L"控制台"), [this, e, data] {
            active_ = e; e->currentDb = data->db; hooks_.newQuery(e, data->db);
        });
        add(tr(L"执行 SQL 文件"), [this, e, data] { ExecuteSqlFile(e, data->db); });
        {   // 转储 SQL 文件 ▶ — export this database's DDL (+ optional data) to .sql
            auto* sub = new wxMenu;
            wxMenuItem* mAll = sub->Append(wxID_ANY, tr(L"结构和数据"));
            sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                DumpDatabase(e, data->db, /*withData*/ true);
            }, mAll->GetId());
            wxMenuItem* mStruct = sub->Append(wxID_ANY, tr(L"仅结构"));
            sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                DumpDatabase(e, data->db, /*withData*/ false);
            }, mStruct->GetId());
            menu.AppendSubMenu(sub, tr(L"转储 SQL 文件"));
        }
        {   // 同步到… ▶ — cross-database structure / data synchronization wizard.
            // Source is this (live) database node; target is chosen in the wizard.
            auto* sub = new wxMenu;
            auto addSync = [&](const wxString& label, int m) {
                wxMenuItem* mi = sub->Append(wxID_ANY, label);
                sub->Bind(wxEVT_MENU, [this, e, data, m](wxCommandEvent&) {
                    SyncDatabase(e, data->db, m);
                }, mi->GetId());
            };
            addSync(tr(L"结构同步"),       0);
            addSync(tr(L"数据同步"),       1);
            addSync(tr(L"结构和数据同步"), 2);
            menu.AppendSubMenu(sub, tr(L"同步到"));
        }
        addOff(tr(L"打印数据库"));
        addOff(tr(L"逆向数据库到模型"));   // needs an ER-view hook in MainFrame — TODO
        addOff(tr(L"在数据库中查找"));
        menu.AppendSeparator();
        add(tr(L"刷新"), [this, item, e, data] {
            data->loaded = false; LoadCategories(item, e, data->db); tree_->Expand(item);
        });
        break;
    }
    case NodeData::CategoryNode: {
        // Designed from the user's angle (ref: docs/UI/screenshots/10-11-19.jpg):
        // the 表 folder gets creation + import/export + refresh; other folders
        // (视图/函数/触发器) get the lightweight subset that actually applies.
        const bool isTables = (data->cat == Category::Tables);
        const db::Dialect dia = e->conn->GetDialect();

        if (isTables) {
            add(tr(L"新建表"), [this, e, data] {
                active_ = e; e->currentDb = data->db;
                if (hooks_.newQueryWith)
                    hooks_.newQueryWith(e, data->db, NewTableTemplate(e->conn->GetDialect()));
            });
        } else if (data->cat == Category::Views) {
            add(tr(L"新建视图"), [this, e, data] {
                NewObject(e, data->db, ObjectKind::View);
            });
        } else if (data->cat == Category::Functions) {
            if (ObjectCreateSupported(ObjectKind::Function, dia))
                add(tr(L"新建函数"), [this, e, data] {
                    NewObject(e, data->db, ObjectKind::Function);
                });
            else
                addOff(tr(L"新建函数"));   // dialect not yet runnable via the SQL splitter
        } else if (data->cat == Category::Procedures) {
            if (ObjectCreateSupported(ObjectKind::Procedure, dia))
                add(tr(L"新建存储过程"), [this, e, data] {
                    NewObject(e, data->db, ObjectKind::Procedure);
                });
            else
                addOff(tr(L"新建存储过程"));
        }
        add(tr(L"新建SQL"), [this, e, data] {
            active_ = e; e->currentDb = data->db; hooks_.newQuery(e, data->db);
        });

        if (isTables) {
            menu.AppendSeparator();
            // 导入 = run a .sql script into this database; 导出 = dump every table.
            add(tr(L"导入 SQL 文件"), [this, e, data] { ExecuteSqlFile(e, data->db); });
            {
                auto* sub = new wxMenu;
                wxMenuItem* mAll = sub->Append(wxID_ANY, tr(L"结构和数据"));
                sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                    DumpDatabase(e, data->db, /*withData*/ true);
                }, mAll->GetId());
                wxMenuItem* mStruct = sub->Append(wxID_ANY, tr(L"仅结构"));
                sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                    DumpDatabase(e, data->db, /*withData*/ false);
                }, mStruct->GetId());
                menu.AppendSubMenu(sub, tr(L"导出为 SQL 文件"));
            }
            // 粘贴表 — recreate a table copied (复制表) from any connection into
            // this database (structure + data), via the async runner.
            {
                wxMenuItem* mp = menu.Append(wxID_ANY, tr(L"粘贴表"));
                if (tableClip_.entry && !tableClip_.table.IsEmpty())
                    menu.Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                        PasteTable(e, data->db);
                    }, mp->GetId());
                else
                    mp->Enable(false);   // nothing on the clipboard yet
            }
            addOff(tr(L"在数据库中查找"));   // honest placeholder — search not wired yet
        }

        menu.AppendSeparator();
        add(tr(L"刷新"), [this, item, data] {
            data->loaded = false; LoadCategoryMembers(item); tree_->Expand(item);
        });
        break;
    }
    case NodeData::Table:
        // Routine leaves (函数/存储过程) get a routine-specific menu, not the table
        // ops (打开表/设计表/…) which don't apply. Build it and stop here.
        if (data->cat == Category::Functions || data->cat == Category::Procedures) {
            const ObjectKind k = (data->cat == Category::Procedures)
                                     ? ObjectKind::Procedure : ObjectKind::Function;
            const db::Dialect dia = e->conn->GetDialect();
            const bool runnable = ObjectCreateSupported(k, dia);
            if (runnable)
                add(tr(L"修改"), [this, e, data, k] { ModifyObject(e, data->db, data->table, k); });
            else
                addOff(tr(L"修改"));
            const bool isProc = (data->cat == Category::Procedures);
            if (runnable)
                add(isProc ? tr(L"新建存储过程") : tr(L"新建函数"),
                    [this, e, data, k] { NewObject(e, data->db, k); });
            else
                addOff(isProc ? tr(L"新建存储过程") : tr(L"新建函数"));
            menu.AppendSeparator();
            // 执行 — prompt for parameters, then run CALL/SELECT (MySQL/PG path,
            // which the SQL splitter runs cleanly). Oracle needs SELECT … FROM DUAL
            // and CALL-block wrapping → gated off with the create path for now.
            if (runnable)
                add(tr(L"执行"),
                    [this, e, data, isProc] { ExecuteRoutine(e, data->db, data->table, isProc); });
            else
                addOff(tr(L"执行"));
            // 编译 — Oracle/DM only (ALTER … COMPILE). MySQL/PG have no COMPILE → greyed.
            if (dia == db::Dialect::Oracle)
                add(tr(L"编译"), [this, e, data, k] { CompileObject(e, data->db, data->table, k); });
            else
                addOff(tr(L"编译"));
            menu.AppendSeparator();
            add(tr(L"删除"), [this, item, e, data, k] {
                DropObject(e, data->db, data->table, k); RefreshTableCategory(item);
            });
            add(tr(L"刷新"), [this, item] { RefreshTableCategory(item); });
            break;
        }
        // View leaves get a DEDICATED menu (like routines) and stop here — the shared
        // table ops below don't apply to a view: 设计表 has no view designer, 删除表
        // (DROP TABLE) and 清空表 (TRUNCATE) error on a view, 重命名/复制/导出表 are
        // table-shaped. A view still *browses* like a table, so 打开视图 reuses the
        // data-grid hook; 复制 CREATE 语句 fetches the view's CREATE via GetCreateDdl.
        if (data->cat == Category::Views) {
            add(tr(L"打开视图"), [this, e, data] {
                active_ = e; e->currentDb = data->db;
                hooks_.openTable(e, data->db, data->table);
            });
            add(tr(L"修改视图"), [this, e, data] {
                ModifyObject(e, data->db, data->table, ObjectKind::View);
            });
            add(tr(L"新建视图"), [this, e, data] {
                NewObject(e, data->db, ObjectKind::View);
            });
            menu.AppendSeparator();
            add(tr(L"删除视图"), [this, item, e, data] {
                DropObject(e, data->db, data->table, ObjectKind::View); RefreshTableCategory(item);
            });
            add(tr(L"复制视图名"),       [this, data] { CopyTableName(data->table); });
            add(tr(L"复制 CREATE 语句"), [this, e, data] { CopyTableDdl(e, data->db, data->table); });
            menu.AppendSeparator();
            add(tr(L"刷新"), [this, item] { RefreshTableCategory(item); });
            break;
        }
        // Designed from the user's angle (ref: docs/UI/screenshots/10-24-08.jpg),
        // grouped: open/design/new · destructive · copy · import/export · refresh.
        add(tr(L"打开表"), [this, e, data] {
            active_ = e; e->currentDb = data->db;
            hooks_.openTable(e, data->db, data->table);
        });
        add(tr(L"设计表"), [this, e, data] {
            active_ = e; e->currentDb = data->db;
            hooks_.designTable(e, data->db, data->table);
        });
        add(tr(L"新建表"), [this, e, data] {
            active_ = e; e->currentDb = data->db;
            if (hooks_.newQueryWith)
                hooks_.newQueryWith(e, data->db, NewTableTemplate(e->conn->GetDialect()));
        });
        menu.AppendSeparator();
        add(tr(L"删除表"),   [this, item, e, data] { DropTable(e, data->db, data->table); RefreshTableCategory(item); });
        add(tr(L"清空表"),   [this, e, data] { EmptyTable(e, data->db, data->table); });
        add(tr(L"重命名"),  [this, item, e, data] { RenameTable(e, data->db, data->table); RefreshTableCategory(item); });
        menu.AppendSeparator();
        // 复制表 — capture this table for a later 粘贴 into another database.
        add(tr(L"复制表"),        [this, e, data] { CopyTable(e, data->db, data->table); });
        add(tr(L"复制表名"),      [this, data] { CopyTableName(data->table); });
        add(tr(L"复制 CREATE 语句"), [this, e, data] { CopyTableDdl(e, data->db, data->table); });
        menu.AppendSeparator();
        {   // 导出表 ▶ — single-table dump (async, reuses DumpScriptDialog).
            auto* sub = new wxMenu;
            wxMenuItem* mAll = sub->Append(wxID_ANY, tr(L"结构和数据"));
            sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                ExportTable(e, data->db, data->table, /*withData*/ true);
            }, mAll->GetId());
            wxMenuItem* mStruct = sub->Append(wxID_ANY, tr(L"仅结构"));
            sub->Bind(wxEVT_MENU, [this, e, data](wxCommandEvent&) {
                ExportTable(e, data->db, data->table, /*withData*/ false);
            }, mStruct->GetId());
            menu.AppendSubMenu(sub, tr(L"导出表"));
        }
        add(tr(L"导入 SQL 文件"), [this, e, data] { ExecuteSqlFile(e, data->db); });
        menu.AppendSeparator();
        add(tr(L"刷新"),      [this, item] { RefreshTableCategory(item); });
        add(tr(L"对象信息"), [this, e, data] { ObjectInfo(e, data->db, data->table); });
        break;
    }
    // 分组 items last, after each node kind's own menu: 移动到分组 / 新建分组 where
    // they apply, no-op where they don't (a database node has no group concept).
    AppendGroupMenu(menu, item, data);
    tree_->PopupMenu(&menu);
}

// ---------------------------------------------------------------------------
// Object editors (视图 / 函数 / 存储过程 / 包).
// ---------------------------------------------------------------------------
void ConnectionTree::NewObject(ConnEntry* e, const wxString& db, ObjectKind kind)
{
    if (!e || !e->IsConnected() || !hooks_.newObjectEditor) return;
    active_ = e; e->currentDb = db;
    const db::Dialect d = e->conn->GetDialect();
    hooks_.newObjectEditor(e, db, ObjectNewTitle(kind), ObjectTemplate(kind, d), kind);
}

void ConnectionTree::ModifyObject(ConnEntry* e, const wxString& db,
                                  const wxString& name, ObjectKind kind)
{
    if (!e || !e->IsConnected() || name.IsEmpty() || !hooks_.newObjectEditor) return;
    active_ = e; e->currentDb = db;
    db::IConnection* c = e->conn.get();
    const db::Dialect d = c->GetDialect();

    // Fetch the object's current definition (synchronous, like 复制 CREATE 语句).
    wxString ddl, err;
    bool ok = false;
    if (kind == ObjectKind::View) {
        ok = c->GetViewDdl(db, name, ddl, err);
    } else {   // Function / Procedure
        db::RoutineInfo r;
        r.name = name;
        r.type = (kind == ObjectKind::Procedure) ? L"PROCEDURE" : L"FUNCTION";
        ok = c->GetRoutineDdl(db, r, ddl, err);
    }
    if (!ok) {
        wxMessageBox(tr(L"读取对象定义失败:") + L"\n\n" + err, tr(L"修改"),
                     wxOK | wxICON_ERROR, dialogParent_);
        return;
    }
    hooks_.newObjectEditor(e, db, name, ObjectModifyDdl(kind, d, name, ddl), kind);
}

// Prompt for parameters, then run the routine in a fresh query tab so its result
// (a procedure's OUT/result set, or a function's returned value) lands in the
// shared results grid — no bespoke result surface.
void ConnectionTree::ExecuteRoutine(ConnEntry* e, const wxString& db,
                                    const wxString& name, bool isProcedure)
{
    if (!e || !e->IsConnected() || name.IsEmpty() || !hooks_.newQueryRun) return;
    active_ = e; e->currentDb = db;
    const db::Dialect d = e->conn->GetDialect();

    RoutineExecDialog dlg(dialogParent_, name, isProcedure, d);
    if (dlg.ShowModal() != wxID_OK) return;
    const wxString sql = dlg.CallStatement();
    if (sql.IsEmpty()) return;
    hooks_.newQueryRun(e, db, sql);
}

// Oracle/DM only: ALTER {FUNCTION|PROCEDURE|PACKAGE} <name> COMPILE. On failure a
// resizable error window shows the full diagnostics with a 复制 button. Callers
// gate this menu item off for engines without a COMPILE concept (MySQL/PG).
void ConnectionTree::CompileObject(ConnEntry* e, const wxString& db,
                                   const wxString& name, ObjectKind kind)
{
    if (!e || !e->IsConnected() || name.IsEmpty()) return;
    active_ = e; e->currentDb = db;
    db::IConnection* c = e->conn.get();

    wxString type;
    switch (kind) {
    case ObjectKind::Function:  type = L"FUNCTION";  break;
    case ObjectKind::Procedure: type = L"PROCEDURE"; break;
    case ObjectKind::Package:   type = L"PACKAGE";   break;
    default: return;
    }
    const wxString sql = L"ALTER " + type + L" " +
                         db::QuoteIdent(name, c->GetDialect()) + L" COMPILE";

    db::QueryResult r;
    wxString err;
    if (c->Execute(sql, r, err)) {
        if (hooks_.status) hooks_.status(wxString::Format(tr(L"%s 编译成功"), name));
        wxMessageBox(wxString::Format(tr(L"%s 编译成功"), name), tr(L"编译"),
                     wxOK | wxICON_INFORMATION, dialogParent_);
    } else {
        ShowSqlError(dialogParent_, tr(L"编译错误"), err);
    }
}

// Refresh the 表 folder in the tree (Category is internal, so this thin wrapper lets
// MainFrame's object-list tab keep the sidebar in sync after a 删除表).
void ConnectionTree::RefreshTablesUi(ConnEntry* e, const wxString& db)
{
    RefreshCategory(e, db, Category::Tables);
}

// Map an object kind to the tree folder its instances live in, then reload that
// folder. Package has no dedicated category folder in the sidebar, so it's a no-op.
void ConnectionTree::RefreshCategory(ConnEntry* e, const wxString& db, ObjectKind kind)
{
    switch (kind) {
    case ObjectKind::View:      RefreshCategory(e, db, Category::Views);      break;
    case ObjectKind::Function:  RefreshCategory(e, db, Category::Functions);  break;
    case ObjectKind::Procedure: RefreshCategory(e, db, Category::Procedures); break;
    case ObjectKind::Package:   break;   // no Packages folder in the tree
    }
}

// Reload the (db, cat) folder in the tree so a just-created / renamed object shows
// up. Located by walking the connection node's children for the database, then that
// database's children for the category folder. Silent no-op when the entry is dead,
// the database isn't opened (categories not built), or the folder was never expanded
// (still shows its 加载中… placeholder — a fresh lazy-load will include the new
// object). Must run on the GUI thread (it mutates tree nodes + kicks the loader).
void ConnectionTree::RefreshCategory(ConnEntry* e, const wxString& db, Category cat)
{
    // The walk itself is FindCategoryNode (ConnectionTree_Groups.cpp), shared
    // with the 分组 code which needs to locate the same folder to repaint it.
    // Two copies of "find the (db, cat) node" is how the two would drift into
    // disagreeing about which folder they are talking about.
    const wxTreeItemId catNode = FindCategoryNode(e, db, cat);
    if (!catNode.IsOk()) return;
    auto* cd = dynamic_cast<NodeData*>(tree_->GetItemData(catNode));
    if (!cd || !cd->loaded) return;   // folder never expanded → lazy-load will show it later
    cd->loaded = false;
    LoadCategoryMembers(catNode);     // async reload; keep it expanded as it already was
    tree_->Expand(catNode);
}

// ---------------------------------------------------------------------------
// Incremental sidebar search (SearchJump) — see ConnectionTree.h for behavior and
// the lazy-load caveat.

// Depth-first flatten of every NodeData-tagged node under `parent`, in the tree's
// natural (visible) order. The "加载中…" lazy-load placeholders are appended without
// a wxTreeItemData, so gating on a non-null GetItemData skips them. `parent` itself
// is never added (callers pass the hidden root_).
void ConnectionTree::CollectSearchNodes(const wxTreeItemId& parent,
                                        std::vector<wxTreeItemId>& out) const
{
    if (!parent.IsOk()) return;
    wxTreeItemIdValue cookie;
    for (wxTreeItemId child = tree_->GetFirstChild(parent, cookie); child.IsOk();
         child = tree_->GetNextChild(parent, cookie)) {
        if (tree_->GetItemData(child))   // real node (placeholders carry none)
            out.push_back(child);
        CollectSearchNodes(child, out);  // recurse into already-loaded descendants
    }
}

// Un-bold the node highlighted by the previous SearchJump, if it is still a live node.
void ConnectionTree::ClearSearchHighlight()
{
    if (searchBold_.IsOk() && tree_->GetItemData(searchBold_))
        tree_->SetItemBold(searchBold_, false);
    searchBold_ = wxTreeItemId{};
}

bool ConnectionTree::SearchJump(const wxString& query, bool next)
{
    if (!tree_ || !root_.IsOk()) return false;
    ClearSearchHighlight();   // drop the previous round's bold highlight

    wxString q = query.Lower();
    q.Trim(true).Trim(false);
    if (q.IsEmpty()) return true;   // cleared box → highlight dropped, tree left as-is

    std::vector<wxTreeItemId> nodes;
    CollectSearchNodes(root_, nodes);

    // Case-insensitive substring match on the node label; record positions so "next"
    // can advance relative to the current selection.
    std::vector<size_t> matches;
    for (size_t i = 0; i < nodes.size(); ++i)
        if (tree_->GetItemText(nodes[i]).Lower().Contains(q))
            matches.push_back(i);

    if (matches.empty()) {
        if (hooks_.status) hooks_.status(tr(L"无匹配"));
        return false;
    }

    // Target: the first match by default; for "next", the first match strictly after
    // the current selection, wrapping back to matches.front() when past the last one.
    size_t targetIdx = matches.front();
    if (next) {
        wxTreeItemId sel = tree_->GetSelection();
        int selPos = -1;
        if (sel.IsOk())
            for (size_t i = 0; i < nodes.size(); ++i)
                if (nodes[i] == sel) { selPos = static_cast<int>(i); break; }
        for (size_t m : matches)
            if (static_cast<int>(m) > selPos) { targetIdx = m; break; }
    }

    wxTreeItemId target = nodes[targetIdx];
    if (!target.IsOk()) return false;
    tree_->EnsureVisible(target);   // expands ancestors so the match is on-screen
    tree_->SelectItem(target);
    tree_->ScrollTo(target);
    tree_->SetItemBold(target, true);
    searchBold_ = target;
    return true;
}

} // namespace ui
