// PgSql.cpp — implementations of the connection-free PostgreSQL SQL-rendering
// helpers declared in PgSql.h. Moved out of PgDriver.cpp to keep that file within
// the 1000-line charter limit; behavior is unchanged.
#include "db/PgSql.h"

namespace db {
namespace detail {
namespace {

// Double-quote + comma-join a column-name list.
wxString JoinIdentsPg(const std::vector<wxString>& cols)
{
    wxString s;
    for (size_t i = 0; i < cols.size(); ++i)
        s += (i ? L", " : L"") + QuoteIdent(cols[i], Dialect::Postgres);
    return s;
}

// Column-set equality (ordered) — used to skip a PK's implicit unique index.
bool SameCols(const std::vector<wxString>& a, const std::vector<wxString>& b)
{
    if (a.size() != b.size() || a.empty()) return false;
    for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) return false;
    return true;
}

// ColKind → a PG-native type name (cross-engine createTable fallback, when the
// source engine tagged the column with a known kind). Widths/scale are appended
// by PgTypeText. Honest gate: coarse (Integer→integer loses int2/int8 width;
// Time/Timestamp drop time-zone variants).
wxString PgTypeFromKind(ColKind k)
{
    switch (k) {
    case ColKind::Integer:   return L"integer";
    case ColKind::Decimal:   return L"numeric";
    case ColKind::Float:     return L"double precision";
    case ColKind::Boolean:   return L"boolean";
    case ColKind::Char:      return L"character";
    case ColKind::Varchar:   return L"character varying";
    case ColKind::Text:      return L"text";
    case ColKind::Binary:
    case ColKind::Blob:      return L"bytea";
    case ColKind::Date:      return L"date";
    case ColKind::Time:      return L"time";
    case ColKind::Timestamp: return L"timestamp";
    case ColKind::Json:      return L"jsonb";
    case ColKind::Uuid:      return L"uuid";
    case ColKind::Enum:      return L"text";
    default:                 return L"text";
    }
}

// A column's DEFAULT clause value. A same-engine PG default_expr from
// information_schema is already a complete PG expression (e.g. "'x'::text",
// "nextval('s'::regclass)", "now()") — emit it verbatim so it round-trips.
// (Cross-engine defaults may need manual review — honest gate.)
wxString PgDefault(const wxString& v) { return v; }

} // namespace

wxString PgTypeText(const NormColumn& c)
{
    // rawType, when present, is authoritative and used verbatim — the original
    // ternary here had this backwards (it discarded a present rawType whenever
    // c.kind was already known and used the empty rawType when it wasn't). By
    // the time a NormColumn reaches this function, rawType is either genuine
    // PG-native text from same-dialect introspection (PgSchemaRead.cpp, A2) or
    // has already been translated to PG-native text upstream by the sync
    // type-mapping layer (SyncTypeMap/DialectProfile::Render, A1/A3/A4) — so a
    // present rawType never needs re-deriving from `kind`. PgTypeFromKind is
    // only the last-resort fallback for the one case with no text at all.
    wxString t = c.rawType.IsEmpty() ? PgTypeFromKind(c.kind) : c.rawType;
    if (t.IsEmpty()) t = L"text";
    // PG's information_schema data_type omits the length modifier; append it for
    // the length-bearing types when GetTableSchema captured one.
    if (!t.Contains(L"(") && c.length >= 0) {
        const wxString lo = t.Lower();
        if (lo == L"character varying" || lo == L"varchar" ||
            lo == L"character" || lo == L"char" ||
            lo == L"bit" || lo == L"bit varying")
            t += wxString::Format(L"(%lld)", c.length);
        else if (lo == L"numeric" || lo == L"decimal")
            t += (c.scale >= 0)
                     ? wxString::Format(L"(%lld,%d)", c.length, c.scale)
                     : wxString::Format(L"(%lld)", c.length);
    }
    return t;
}

// An identity column can't also carry a DEFAULT, so DEFAULT is suppressed there.
// Note: PgSchemaRead.cpp (A2) sets autoIncrement=true for both nextval()-backed
// serial columns and PG10+ GENERATED ... AS IDENTITY columns, so both now
// render as IDENTITY here — a deliberate approximation (a re-created serial
// column becomes an identity column, not literally serial syntax again).
wxString PgColumnDef(const NormColumn& c)
{
    wxString s = QuoteIdent(c.name, Dialect::Postgres) + L" " + PgTypeText(c);
    if (c.autoIncrement) s += L" GENERATED BY DEFAULT AS IDENTITY";
    if (c.notNull)       s += L" NOT NULL";
    if (c.hasDefault && !c.autoIncrement)
        s += L" DEFAULT " + PgDefault(c.defaultExpr);
    return s;
}

// Takes the table's IDENTITY and quotes it here, so both callers -- the
// CREATE TABLE renderer and the schema-change renderer -- get the same
// schema-qualified relation without either having to pre-quote.
wxString RenderCreateIndexPg(const QualifiedName& table, const NormIndex& idx)
{
    wxString s = idx.unique ? L"CREATE UNIQUE INDEX " : L"CREATE INDEX ";
    s += QuoteIdent(idx.name, Dialect::Postgres) + L" ON " +
         QualifiedTableSql(wxString(), table, Dialect::Postgres) + L" (" +
         JoinIdentsPg(idx.columns) + L")";
    return s;
}

wxString RenderFkConstraintPg(const NormForeignKey& fk)
{
    wxString s;
    if (!fk.name.IsEmpty())
        s = L"CONSTRAINT " + QuoteIdent(fk.name, Dialect::Postgres) + L" ";
    s += L"FOREIGN KEY (" + JoinIdentsPg(fk.columns) + L") REFERENCES " +
         QuoteIdent(fk.refTable, Dialect::Postgres) + L" (" +
         JoinIdentsPg(fk.refColumns) + L")";
    if (!fk.onDelete.IsEmpty()) s += L" ON DELETE " + fk.onDelete;
    if (!fk.onUpdate.IsEmpty()) s += L" ON UPDATE " + fk.onUpdate;
    return s;
}

void RenderCreateTablePg(const TableSchema& s, std::vector<wxString>& stmts)
{
    // Schema-qualified: rendering a bare name here would CREATE the table in
    // whatever search_path resolves to rather than the schema the plan named.
    const wxString t = QualifiedTableSql(wxString(), s.name, Dialect::Postgres);
    std::vector<wxString> defs;
    for (const auto& c : s.columns) defs.push_back(L"  " + PgColumnDef(c));
    if (!s.primaryKey.empty())
        defs.push_back(L"  PRIMARY KEY (" + JoinIdentsPg(s.primaryKey) + L")");

    wxString sql = L"CREATE TABLE " + t + L" (\n";
    for (size_t i = 0; i < defs.size(); ++i)
        sql += defs[i] + (i + 1 < defs.size() ? L",\n" : L"\n");
    sql += L")";
    stmts.push_back(sql);

    for (const auto& idx : s.indexes) {
        if (idx.primary) continue;
        if (idx.unique && SameCols(idx.columns, s.primaryKey)) continue;
        stmts.push_back(RenderCreateIndexPg(s.name, idx));
    }
    for (const auto& fk : s.foreignKeys)
        stmts.push_back(L"ALTER TABLE " + t + L" ADD " + RenderFkConstraintPg(fk));
}

} // namespace detail
} // namespace db
