// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 SwiftSQL Contributors

// PgSql.h — pure SQL-rendering helpers for the PostgreSQL driver. Dialect-
// specific but connection-free: they turn normalized schema value objects
// (SchemaModel.h) into PostgreSQL DDL text. Split out of PgDriver.cpp so that
// file stays within the 1000-line charter limit; RenderSchemaChange calls into
// here. Nothing in this unit touches a PGconn* handle.
#pragma once

#include <wx/string.h>
#include <vector>

#include "db/DbDriver.h"   // Dialect / QuoteIdent (+ transitively SchemaModel.h)

namespace db {
namespace detail {

// Column type text. rawType, when present, is authoritative and used verbatim
// — true whether it is genuine same-dialect PG introspection text or has
// already been translated to PG-native syntax upstream (SyncTypeMap /
// DialectProfile::Render). Only an EMPTY rawType falls back to mapping `kind`
// via PgTypeFromKind. Length/scale appended for length-bearing types.
wxString PgTypeText(const NormColumn& c);

// `"col" <type> [GENERATED BY DEFAULT AS IDENTITY] [NOT NULL] [DEFAULT …]`.
wxString PgColumnDef(const NormColumn& c);

// CREATE [UNIQUE] INDEX "idx" ON "t" ("c1","c2").
wxString RenderCreateIndexPg(const QualifiedName& table, const NormIndex& idx);

// [CONSTRAINT "fk"] FOREIGN KEY (…) REFERENCES "rt" (…) [ON DELETE/UPDATE …] —
// the tail after ADD in an ALTER TABLE.
wxString RenderFkConstraintPg(const NormForeignKey& fk);

// Whole new table: CREATE TABLE (columns + inline PRIMARY KEY) pushed first, then
// each secondary index and FK as its own statement (PG indexes are schema-level
// objects). The PK's implicit unique index is skipped.
void RenderCreateTablePg(const TableSchema& s, std::vector<wxString>& stmts);

} // namespace detail
} // namespace db
