// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 SwiftSQL Contributors

// LangPackEn.cpp — built-in English language pack (pure data). Maps each
// Chinese source string to its English translation, as a flat
// {source, translation, …, nullptr} array. Add a new in-code language by
// cloning this file (LangPackXx.cpp) and registering it in Lang.cpp; or drop an
// external lang/<code>.ini next to the executable — no code changes needed.
#include <cwchar>

namespace core {

// `extern` forces external linkage — namespace-scope const arrays are internal
// by default, which would hide this from Lang.cpp.
extern const wchar_t* const kLangPackEn[] = {
    // ---- menu bar ----
    L"文件(&F)", L"File(&F)",
    L"编辑(&E)", L"Edit(&E)",
    L"查看(&V)", L"View(&V)",
    L"收藏(&B)", L"Favourites(&B)",
    L"工具(&T)", L"Tools(&T)",
    L"窗口(&W)", L"Window(&W)",
    L"帮助(&H)", L"Help(&H)",
    // bare top-strip titles (the custom menu row uses tr(L"文件") without the mnemonic)
    L"文件", L"File",
    L"编辑", L"Edit",
    L"查看", L"View",
    L"收藏", L"Favourites",
    L"工具", L"Tools",
    L"窗口", L"Window",
    L"帮助", L"Help",
    // ---- file menu ----
    L"新建连接(&N)\tCtrl+N", L"New Connection(&N)\tCtrl+N",
    L"新建SQL(&Q)\tCtrl+T",   L"New SQL(&Q)\tCtrl+T",
    L"打开 SQL 文件(&O)\tCtrl+O", L"Open SQL File(&O)\tCtrl+O",
    L"保存(&S)\tCtrl+S",       L"Save(&S)\tCtrl+S",
    L"退出(&X)",               L"Exit(&X)",
    // ---- edit menu ----
    L"撤销(&U)\tCtrl+Z", L"Undo(&U)\tCtrl+Z",
    L"重做(&R)\tCtrl+Y", L"Redo(&R)\tCtrl+Y",
    L"剪切(&T)\tCtrl+X", L"Cut(&T)\tCtrl+X",
    L"复制(&C)\tCtrl+C", L"Copy(&C)\tCtrl+C",
    L"粘贴(&P)\tCtrl+V", L"Paste(&P)\tCtrl+V",
    // ---- view / favourites / tools / window / help menus ----
    L"SQL 编辑器",  L"SQL Editor",
    L"表设计",      L"Table Design",
    L"ER 图",       L"ER Diagram",
    L"收藏当前查询", L"Favourite Current Query",
    L"导入向导",   L"Import Wizard",
    L"导出向导",   L"Export Wizard",
    L"备份",       L"Backup",
    L"偏好设置",   L"Preferences",
    L"下一个标签页\tCtrl+Tab", L"Next Tab\tCtrl+Tab",
    L"关于 SwiftSQL(&A)", L"About SwiftSQL(&A)",
    // ---- toolbar ----
    L"新建连接", L"New Conn",
    L"新建SQL", L"New SQL",
    L"  新建SQL  ", L"  New SQL  ",
    L"表",       L"Table",
    L"视图",     L"View",
    L"函数",     L"Function",
    L"模型",     L"Model",
    L"备份",     L"Backup",
    L"导入",     L"Import",
    L"导出",     L"Export",
    L"自动运行", L"Automation",
    L"  AI 生成 SQL  ", L"  AI Gen SQL  ",
    // ---- view switch segments ----
    L"  SQL 编辑器  ", L"  SQL Editor  ",
    L"  表设计  ",     L"  Table Design  ",
    L"  ER 图  ",      L"  ER Diagram  ",
    // ---- connection lifecycle ----
    L"SSH 隧道失败:",      L"SSH tunnel failed: ",
    L"连接失败:",         L"Connection failed: ",
    L"未配置 Oracle 客户端", L"Oracle Client Not Configured",
    L"连接 Oracle 需要 OCI 客户端库(oci.dll),当前未找到。是否现在去偏好设置配置?",
        L"Connecting to Oracle needs the OCI client library (oci.dll), which wasn't found. Configure it in Preferences now?",
    L"已连接",            L"Connected",
    L"获取数据库列表失败:", L"Failed to list databases: ",
    L"(读取表失败)",      L"(failed to read tables)",
    L"搜索表、视图…",      L"Search tables, views…",
    // ---- tree context menu ----
    L"连接",       L"Connect",
    L"打开连接",   L"Open Connection",
    L"断开连接",   L"Disconnect",
    L"打开数据库", L"Open Database",
    L"关闭数据库", L"Close Database",
    L"刷新",       L"Refresh",
    L"编辑连接",  L"Edit Connection",
    L"复制连接",  L"Duplicate Connection",
    L"副本",       L"copy",
    L"删除连接",   L"Delete Connection",
    L"确定删除此连接?", L"Delete this connection?",
    L"新建数据库",  L"New Database",
    L"数据库名称:", L"Database name: ",
    L"新建数据库失败:", L"Failed to create database: ",
    L"打开表",     L"Open Table",
    L"已断开",     L"Disconnected",
    // ---- data grid editing ----
    L"+ 行",       L"+ Row",
    L"− 行",       L"− Row",
    L"保存修改",   L"Save Changes",
    L"仅单表查询且有主键时可编辑数据", L"Editable only for single-table SELECT with a primary key",
    L"没有检测到数据改动。", L"No data changes detected.",
    L"将对数据库执行以下修改:", L"The following changes will be applied:",
    L"确认执行?", L"Execute?",
    L"保存数据修改", L"Save Data Changes",
    L"开启事务失败:", L"Failed to start transaction:",
    L"执行失败,已回滚:", L"Execution failed, rolled back:",
    L"数据已保存", L"Data saved",
    L"取消(放弃未保存的修改)", L"Cancel (discard unsaved changes)",
    L"没有待放弃的修改", L"No changes to discard",
    L"已应用到事务(未提交)", L"Applied to transaction (not committed)",
    L"执行失败(事务仍开启,可回滚):", L"Execution failed (transaction still open, can roll back): ",
    L"保存并提交事务", L"Save and Commit Transaction",
    L"确定要保存这 %d 项修改并提交事务吗?", L"Save these %d change(s) and commit the transaction?",
    L"数据已保存,事务已提交", L"Data saved; transaction committed",
    // ---- data browser (打开表) ----
    L"查看器",     L"Viewer",
    L"筛选",       L"Filter",
    L"排序",       L"Sort",
    L"文本",       L"Text",
    L"显示",       L"Display",
    L"复制",       L"Copy",
    L"粘贴",       L"Paste",
    L"复制为",     L"Copy As",
    L"SQL (INSERT 语句)", L"SQL (INSERT statement)",
    L"SQL (UPDATE 语句)", L"SQL (UPDATE statement)",
    L"SQL (DELETE 语句)", L"SQL (DELETE statement)",
    L"需要有主键的单表结果才能生成 UPDATE / DELETE 语句。",
        L"UPDATE / DELETE statements need a single-table result with a primary key.",
    L"纯文本值",   L"Plain text value",
    L"设为空字符串", L"Set Empty String",
    L"设为 NULL",  L"Set NULL",
    L"删除记录",   L"Delete Record",
    L"删除选中的 %d 条记录？", L"Delete the %d selected record(s)?",
    L"复制整行",   L"Copy Row",
    L"粘贴到新行", L"Paste as New Row",
    // ---- filter panel (Navicat-style condition rows) ----
    L"筛选条件",   L"Filter conditions",
    L"包含",       L"contains",
    L"不包含",     L"not contains",
    L"开头为",     L"starts with",
    L"结尾为",     L"ends with",
    L"未填写值，生成时会跳过此行", L"No value — this row is skipped when generating",
    L"与下一条的连接词 (点击切换 AND/OR)", L"Connector to the next row (click to toggle AND/OR)",
    L"在下方添加条件", L"Add a condition below",
    L"手动分组 (即将支持)", L"Manual grouping (coming soon)",
    L"删除此条件", L"Remove this condition",
    L"多值请用英文逗号分隔", L"Separate multiple values with commas",
    L"（无条件）", L"(no condition)",
    L"将数据另存为…", L"Save Data As…",
    L"▲ 升序",     L"▲ Ascending",
    L"▼ 降序",     L"▼ Descending",
    L"▲ 升序（仅此列）", L"▲ Ascending (this column only)",
    L"▼ 降序（仅此列）", L"▼ Descending (this column only)",
    L"＋ 加入多列排序", L"＋ Add to multi-sort",
    L"升序排序",   L"Sort Ascending",
    L"降序排序",   L"Sort Descending",
    // ---- multi-column sort panel + column picker ----
    L"+ 添加排序列", L"+ Add sort column",
    L"（选择列）", L"(select column)",
    L"升序",       L"Ascending",
    L"降序",       L"Descending",
    L"上移",       L"Move up",
    L"下移",       L"Move down",
    L"删除此排序列", L"Remove this sort column",
    L"（已用）",   L"(in use)",
    L"↑↓ 移动 · Enter 选择 · Esc 取消", L"↑↓ move · Enter select · Esc cancel",
    L"选择列",     L"Select column",
    L"双击或回车选择 · Esc 取消", L"Double-click or Enter to select · Esc to cancel",
    L"确定",       L"OK",
    L"应用",       L"Apply",
    L"清除",       L"Clear",
    L"隐藏此列",   L"Hide This Column",
    L"显示所有列", L"Show All Columns",
    L"按此格值筛选", L"Filter by This Value",
    L"排除此格值", L"Exclude This Value",
    L"移除所有筛选与排序", L"Remove All Filters and Sort",
    L"筛选仅适用于单表结果。", L"Filtering applies only to single-table results.",
    L"未保存的修改", L"Unsaved Changes",
    L"当前有未保存的修改。是否先保存,再继续?",
        L"You have unsaved changes. Save before continuing?",
    L"保存",       L"Save",
    L"放弃",       L"Discard",
    // ---- export dialog ----
    L"导出数据",   L"Export Data",
    L"配置",       L"Config",
    L"导出",       L"Export",
    L"（查询结果）", L"(query result)",
    L"当前页",     L"Current page",
    L"整表全部",   L"Whole table",
    L"选中记录",   L"Selected rows",
    L"导出范围",   L"Export scope",
    L"格式",       L"Format",
    L"TXT 分隔符", L"TXT delimiter",
    L"逗号 ,",     L"Comma ,",
    L"分号 ;",     L"Semicolon ;",
    L"竖线 |",     L"Pipe |",
    L"编码",       L"Encoding",
    L"UTF-8 (带 BOM)", L"UTF-8 (with BOM)",
    L"选择导出文件", L"Choose export file",
    L"包含表头行（列名）", L"Include header row (column names)",
    L"覆盖同名文件（不再询问）", L"Overwrite existing file (no prompt)",
    L"开始导出",   L"Start export",
    L"请先选择导出文件。", L"Please choose an export file first.",
    L"文件已存在，是否覆盖？", L"File exists. Overwrite?",
    L"无法写入文件：", L"Cannot write file: ",
    L"正在导出…",  L"Exporting…",
    L"已写入 %lld 行", L"%lld rows written",
    L"导出失败",   L"Export failed",
    L"已停止（文件不完整）", L"Stopped (file incomplete)",
    L"导出完成",   L"Export complete",
    L"共 %lld 行 · 用时 %ld ms", L"%lld rows · %ld ms",
    L"导出数据失败：", L"Data export failed: ",
    L"读取数据失败：", L"Failed to read data: ",
    L"没有可导出的结果。", L"Nothing to export.",
    // ---- import dialog ----
    L"导入数据",   L"Import Data",
    L"导入",       L"Import",
    L"支持 CSV / TXT / JSON / XML；.sql 文件将转交“执行 SQL 脚本”。",
        L"Supports CSV / TXT / JSON / XML; .sql files are handed to \"Run SQL Script\".",
    L"数据文件",   L"Data file",
    L"选择数据文件", L"Choose data file",
    L"目标表",     L"Target table",
    L"首行是列名（CSV/TXT）", L"First row is column names (CSV/TXT)",
    L"遇到错误继续（逐行提交，记录失败）",
        L"Continue on error (row-by-row commit, log failures)",
    L"在事务中导入（全部成功才提交，出错回滚）",
        L"Import in a transaction (commit only if all succeed, else roll back)",
    L"开始导入",   L"Start import",
    L"请填写目标表名。", L"Please enter the target table name.",
    L"无法识别的文件格式（支持 CSV / TXT / JSON / XML / SQL）。",
        L"Unrecognized file format (CSV / TXT / JSON / XML / SQL supported).",
    L"正在解析…",  L"Parsing…",
    L"正在导入…",  L"Importing…",
    L"已处理 %lld 行", L"%lld rows processed",
    L"成功 %lld    失败 %lld", L"OK %lld    Failed %lld",
    L"导入完成",   L"Import complete",
    L"导入完成（有失败）", L"Import complete (with failures)",
    L"成功 %lld · 失败 %lld · 用时 %ld ms", L"OK %lld · Failed %lld · %ld ms",
    L"解析失败",   L"Parse failed",
    L"失败明细",   L"Failure details",
    L"行",         L"Line",
    L"错误信息",   L"Error",
    L"原始行",     L"Raw row",
    L"复制错误",   L"Copy errors",
    L"导出错误…",  L"Export errors…",
    L"# 数据导入错误报告 · 目标 %s · 失败 %zu 条\n\n",
        L"# Data import error report · target %s · %zu failures\n\n",
    L"[行 %lld] %s\n  原始: %s\n\n", L"[line %lld] %s\n  raw: %s\n\n",
    L"尚未连接数据库。", L"Not connected to a database.",
    // ---- bottom-bar icon tooltips ----
    L"增加行",     L"Add Row",
    L"删除行",     L"Delete Row",
    L"提交事务",   L"Commit",
    L"回滚事务",   L"Rollback",
    L"停止查询",   L"Stop",
    L"首页",       L"First Page",
    L"上一页",     L"Previous Page",
    L"下一页",     L"Next Page",
    L"末页",       L"Last Page",
    L"每页行数",   L"Rows per page",
    // ---- favourites ----
    L"收藏 SQL",   L"Favourite SQL",
    L"收藏名称:",  L"Favourite name: ",
    L"已收藏",     L"Favourited",
    L"(暂无收藏)", L"(no favourites yet)",
    // ---- transactions / run ----
    L"开始事务",   L"Begin",
    L"提交",       L"Commit",
    L"回滚",       L"Rollback",
    L"停止",       L"Stop",
    L"事务已开始", L"Transaction started",
    L"事务已提交", L"Transaction committed",
    L"事务已回滚", L"Transaction rolled back",
    L"已请求停止查询", L"Cancel requested",
    L"尚未连接",   L"Not connected",
    L"事务操作失败:", L"Transaction failed: ",
    // ---- status bar / misc ----
    L"就绪 — 点击工具栏「新建连接」开始", L"Ready — click \"New Connection\" on the toolbar",
    // ---- preferences dialog ----
    L"偏好设置", L"Preferences",
    L"语言",     L"Language",
    L"确定",     L"OK",
    L"取消",     L"Cancel",
    L"切换语言后将自动重启应用。", L"The app will restart automatically after changing the language.",
    L"语言已切换,重启应用后生效。", L"Language changed. Restart to apply.",
    L"Oracle 客户端 (OCI 动态库)", L"Oracle Client (OCI dynamic library)",
    L"自动搜索 (程序目录 / PATH)", L"Auto-detect (exe folder / PATH)",
    L"浏览…", L"Browse…",
    L"选择 oci.dll", L"Select oci.dll",
    L"未配置 — 连接 Oracle 时将自动搜索", L"Not set — auto-detected when connecting to Oracle",
    L"✓ 已就绪: ", L"✓ Ready: ",
    L"未找到 (连接 Oracle 时需要)", L"Not found (required to connect to Oracle)",

    // ---- cross-database synchronization (milestone D) ----
    L"同步到",         L"Synchronize to",
    L"结构同步",       L"Structure Sync",
    L"结构和数据同步", L"Structure & Data Sync",
    L"数据同步",        L"Data Sync",
    L"请先在左侧打开一个数据库,再使用数据同步",
        L"Open a database in the sidebar first to use data sync.",
    L"同步内容",        L"What to synchronize",
    L"表结构（列 / 主键 / 索引 / 外键）", L"Table structure (columns / PK / indexes / FKs)",
    L"数据（按主键增量：INSERT / UPDATE，需目标含主键）",
        L"Data (PK-keyed: INSERT / UPDATE; target needs a primary key)",
    L"危险动作策略",    L"Destructive-action policy",
    L"当目标存在源没有的表时：", L"When the target has tables the source doesn't:",
    L"保留目标多余的表（安全，默认）", L"Keep the target's extra tables (safe, default)",
    L"删除目标多余的表（危险，需二次确认）", L"Drop the target's extra tables (dangerous; confirmed)",
    L"在事务中执行（可回滚方言：出错整体回滚；MySQL DDL 不受事务保护）",
        L"Run in a transaction (rollback-capable dialects; MySQL DDL is not protected)",
    L"试运行（只比对、只预览 SQL，不落库）",
        L"Dry run (compare + preview SQL only; no changes applied)",
    L"源 Source",       L"Source",
    L"目标 Target",     L"Target",
    L"源",              L"Source",
    L"目标",            L"Target",
    L"连接类型",        L"Type",
    L"服务器版本",      L"Server version",
    L"互换源与目标",    L"Swap source and target",
    L"请选择源数据库。", L"Select a source database.",
    L"请选择目标连接与数据库。", L"Select a target connection and database.",
    L"源与目标不能是同一个数据库。", L"Source and target can't be the same database.",
    L"暂不支持跨数据库引擎同步（MVP 仅支持同引擎）。",
        L"Cross-engine sync isn't supported yet (same-engine only in this MVP).",
    L"就绪：可进入下一步选择同步内容。", L"Ready — continue to choose what to sync.",
    L"上一步",          L"Back",
    L"下一步 ▸",        L"Next ▸",
    L"预览 SQL ▸",      L"Preview SQL ▸",
    L"执行",            L"Run",
    L"试运行",          L"Dry Run",
    L"保存 Profile",    L"Save Profile",
    L"载入 Profile",    L"Load Profile",
    L"同步方案（Profile）保存 / 载入即将上线。",
        L"Sync-profile save / load is coming soon.",
    L"正在比对源与目标…", L"Comparing source and target…",
    L"准备中…",         L"Preparing…",
    L"正在停止…",       L"Stopping…",
    L"对象",            L"Object",
    L"状态",            L"Status",
    L"摘要",            L"Summary",
    L"勾选要应用的变更。破坏性变更（删除表 / 删除列 / 删除行）默认不勾选。",
        L"Check the changes to apply. Destructive changes (drop table/column, delete rows) are unchecked by default.",
    L"共 %d 项变更 · 已选 %d · 破坏性 %d（默认不勾）",
        L"%d changes · %d selected · %d destructive (unchecked by default)",
    L"＋ 新增",         L"+ Added",
    L"－ 删除",         L"- Dropped",
    L"✎ 结构修改",      L"~ Modified",
    L"⇄ 数据",          L"Data",
    L"＝ 一致",         L"= Identical",
    L"结构+数据",       L"Structure + Data",
    L"%zu 条 DDL",      L"%zu DDL",
    L"SQL 预览",        L"SQL Preview",
    L"导出 .sql…",      L"Export .sql…",
    L"导出 SQL",        L"Export SQL",
    L"危险语句",        L"Destructive statement",
    L"表",              L"Table",
    L"⚠ 含 %d 条破坏性语句（DROP / DELETE / TRUNCATE），执行前将要求键入库名确认。",
        L"⚠ %d destructive statements (DROP / DELETE / TRUNCATE); you'll type the db name to confirm.",
    L"无破坏性语句。",  L"No destructive statements.",
    L"目标已与源一致，没有需要同步的差异。", L"Target already matches the source — nothing to sync.",
    L"比对失败：",      L"Compare failed: ",
    L"试运行完成：以上为将执行的 SQL，本次未落库。",
        L"Dry run done — the SQL above would run; nothing was applied.",
    L"请至少勾选一项变更后再执行。", L"Check at least one change before running.",
    L"同步结束",        L"Sync finished",
    // ---- sync runner ----
    L"执行同步",        L"Run Synchronization",
    L"正在同步…",       L"Synchronizing…",
    L"危险操作确认",    L"Confirm destructive operation",
    L"此操作包含删除 / 清空等破坏性语句，可能造成目标数据不可恢复。\n请键入目标数据库名以确认执行：",
        L"This includes destructive statements (drop/truncate) that may be unrecoverable.\nType the target database name to confirm:",
    L"已取消（未执行）", L"Cancelled (nothing ran)",
    L"库名不匹配或已取消，目标未改变。", L"Name didn't match or cancelled — target unchanged.",
    L"正在执行  %d / %d", L"Running  %d / %d",
    L"已执行 %d 条",    L"%d statements run",
    L"同步完成",        L"Sync complete",
    L"全部语句执行成功 · 用时 %ld ms", L"All statements succeeded · %ld ms",
    L"同步失败",        L"Sync failed",
    L"执行失败：",      L"Execution failed: ",
    L"错误：",          L"Error: ",
    L"已停止 — 按事务策略，未提交的更改已回滚或部分提交。",
        L"Stopped — per the transaction policy, uncommitted changes were rolled back or partly committed.",


    // ---- i18n coverage top-up (audit 2026-07): UI strings not previously packed ----
    L" 字节，图形预览将在后续版本支持）", L" bytes; graphic preview is coming in a future version)",
    L" 已创建。", L" created.",
    L" 条失败语句，等待 AI 分析…\n该功能即将上线：将结合报错信息与语句上下文，给出可能原因与修复建议。", L" failed statement(s), awaiting AI analysis…\nComing soon: it will combine the error and statement context to suggest likely causes and fixes.",
    L" 自动布局 ", L" Auto Layout ",
    L"# SQL 脚本执行错误报告\n# 连接：%s   数据库：%s\n# 失败 %zu 条\n\n", L"# SQL script execution error report\n# Connection: %s   Database: %s\n# %zu failures\n\n",
    L"%d/%d 表%s", L"%d/%d tables%s",
    L"%ld / %zu 张表", L"%ld / %zu tables",
    L"(共 %zu,仅显示前 %zu)", L"(%zu total, showing first %zu)",
    L"(读取失败)", L"(read failed)",
    L"(默认)", L"(default)",
    L"-- 尚无字段，先在“字段”页添加列", L"-- No fields yet — add columns on the \\\"Fields\\\" tab first",
    L"-- 无待执行的结构变更", L"-- No pending structure changes",
    L"-- 获取 DDL 失败:", L"-- Failed to get DDL: ",
    L"-- 请输入数据库名称", L"-- Enter a database name",
    L"AI 诊断", L"AI Diagnosis",
    L"AI 诊断（预览）\n————————————————\n已收集 ", L"AI Diagnosis (preview)\n————————————————\nCollected ",
    L"Big5 (繁体中文)", L"Big5 (Traditional Chinese)",
    L"CA 证书", L"CA Certificate",
    L"CA 证书路径(可选)", L"CA certificate path (optional)",
    L"ER 关系图", L"ER Diagram",
    L"ERR: 未连接或未选表", L"ERR: not connected or no table selected",
    L"GBK / GB18030 (简体中文)", L"GBK / GB18030 (Simplified Chinese)",
    L"PG search_path / 默认 schema", L"PG search_path / default schema",
    L"SQLite 文件 (*.db;*.sqlite;*.sqlite3)|*.db;*.sqlite;*.sqlite3|所有文件 (*.*)|*.*", L"SQLite files (*.db;*.sqlite;*.sqlite3)|*.db;*.sqlite;*.sqlite3|All files (*.*)|*.*",
    L"SSH 主机", L"SSH Host",
    L"SSH 密码", L"SSH Password",
    L"SSH 用户", L"SSH User",
    L"SSH 端口", L"SSH Port",
    L"SSL 模式(PG)", L"SSL Mode (PG)",
    L"SwiftSQL v0.2.0\n\n轻量、跨平台的 SQL 客户端\n支持 MySQL · PostgreSQL · OceanBase\n\nQuery fast. Ship faster.", L"SwiftSQL v0.2.0\n\nA lightweight, cross-platform SQL client\nSupports MySQL · PostgreSQL · OceanBase\n\nQuery fast. Ship faster.",
    L"SwiftSQL 需要关闭", L"SwiftSQL needs to close",
    L"Unix socket / 命名管道(本地)", L"Unix socket / named pipe (local)",
    L"[第 %d 条] %s\n  语句: %s\n\n", L"[#%d] %s\n  statement: %s\n\n",
    L"\n\n-- 语句:\n", L"\\n\\n-- Statement:\\n",
    L"\n\n-- 语句：\n", L"\\n\\n-- Statement:\\n",
    L"application_name / 程序名", L"application_name / program name",
    L"cipher 列表(可选)", L"cipher list (optional)",
    L"keepalive 间隔(秒)", L"keepalive interval (s)",
    L"✓ 结构已更新", L"✓ Structure updated",
    L"✓ 表 ", L"✓ Table ",
    L"✓ 连接成功(%ld ms)\n\n%s %s @ %s:%d", L"✓ Connected (%ld ms)\n\n%s %s @ %s:%d",
    L"✗ 连接失败\n\n%s", L"✗ Connection failed\n\n%s",
    L"下一步", L"Next",
    L"主机", L"Host",
    L"主键", L"Primary Key",
    L"仅可编辑的单表结果支持从 CSV 导入行", L"Row import from CSV is only supported for editable single-table results",
    L"仅结构", L"Structure only",
    L"会话时区", L"Session Time Zone",
    L"位置: ", L"Location: ",
    L"体积", L"Size",
    L"使用 HTTP 隧道", L"Use HTTP tunnel",
    L"使用 SSH 隧道", L"Use SSH tunnel",
    L"使用 SSL", L"Use SSL",
    L"使用协议压缩", L"Use protocol compression",
    L"例如:Production", L"e.g. Production",
    L"保存外键", L"Save Foreign Keys",
    L"保存密码", L"Save Password",
    L"保存索引", L"Save Indexes",
    L"保存触发器", L"Save Triggers",
    L"保持连接(keepalive)", L"Keep alive (keepalive)",
    L"修改日期", L"Modified Date",
    L"修改时间", L"Modified Time",
    L"共 %d 条 · 成功 %d · 失败 %d · 用时 %ld ms", L"%d total · %d ok · %d failed · %ld ms",
    L"共 %d 条语句", L"%d statements",
    L"共 %d 表 · 成功 %d · %ld 行 · 用时 %ld ms", L"%d tables · %d ok · %ld rows · %ld ms",
    L"共 %zu 张表", L"%zu tables",
    L"关于 SwiftSQL", L"About SwiftSQL",
    L"关闭", L"Close",
    L"关闭其他标签", L"Close Other Tabs",
    L"关闭右侧所有", L"Close Tabs to the Right",
    L"关闭左侧所有", L"Close Tabs to the Left",
    L"关闭当前标签", L"Close Current Tab",
    L"关闭程序", L"Close Application",
    L"关闭表设计", L"Close Table Design",
    L"关闭该表设计标签", L"Close this table-design tab",
    L"写入临时文件出错。", L"Error writing the temporary file.",
    L"写入文件时出错", L"Error writing the file",
    L"创建失败：\n\n", L"Creation failed:\n\n",
    L"创建时间", L"Created Time",
    L"创建选项", L"Create Options",
    L"初始 SQL", L"Init SQL",
    L"初始数据库(可留空)", L"Initial database (optional)",
    L"删除外键", L"Delete Foreign Key",
    L"删除字段", L"Delete Field",
    L"删除数据库", L"Delete Database",
    L"删除数据库失败:", L"Failed to delete database: ",
    L"删除索引", L"Delete Index",
    L"删除表", L"Delete Table",
    L"删除表失败:", L"Failed to delete table: ",
    L"删除触发器", L"Delete Trigger",
    L"删除选中的 %zu 张表", L"Delete %zu selected tables",
    L"别担心 —— SwiftSQL 已经拦下了这个错误，你的数据没有丢失。\n你可以继续使用；如果问题反复出现，请把下面的诊断信息发给我们。", L"Don't worry — SwiftSQL caught this error and your data is safe.\nYou can keep working; if it keeps happening, please send us the diagnostics below.",
    L"加密套件", L"Cipher Suite",
    L"加载中…", L"Loading…",
    L"加载失败", L"Load failed",
    L"加载失败: ", L"Load failed: ",
    L"升序/降序 (点击切换)", L"Ascending/Descending (click to toggle)",
    L"双击左侧表名以查看其结构", L"Double-click a table on the left to view its structure",
    L"双击左侧表名可生成查询，或点「新建SQL」手写 SQL", L"Double-click a table on the left to generate a query, or click \\\"New SQL\\\" to write SQL by hand",
    L"只读连接", L"Read-only connection",
    L"否", L"No",
    L"启动时自动连接", L"Auto-connect on startup",
    L"在事务中执行（全部成功才提交，出错回滚）", L"Run in a transaction (commit only if all succeed, else roll back)",
    L"在数据库中查找", L"Find in Database",
    L"地址", L"Address",
    L"增加字段", L"Add Field",
    L"复制 CREATE 语句", L"Copy CREATE Statement",
    L"复制字段", L"Duplicate Field",
    L"复制表", L"Duplicate Table",
    L"复制表名", L"Copy Table Name",
    L"复制详情", L"Copy Details",
    L"如 +08:00 / Asia/Shanghai(留空=服务器)", L"e.g. +08:00 / Asia/Shanghai (empty = server)",
    L"字段", L"Fields",
    L"字段属性", L"Field Properties",
    L"字段数", L"Field Count",
    L"字符集", L"Charset",
    L"字符集 (CHARACTER SET):", L"Charset (CHARACTER SET):",
    L"存储过程", L"Stored Procedures",
    L"完成 · %d 条语句 · %llu 行 · %ld ms", L"Done · %d statements · %llu rows · %ld ms",
    L"客户端密钥", L"Client Key",
    L"客户端认证", L"Client Authentication",
    L"客户端证书", L"Client Certificate",
    L"密码", L"Password",
    L"密钥密码短语", L"Key Passphrase",
    L"对象信息", L"Object Info",
    L"导入 SQL 文件", L"Import SQL File",
    L"导出为 SQL 文件", L"Export as SQL File",
    L"导出数据失败 — ", L"Data export failed — ",
    L"导出结束", L"Export finished",
    L"导出表", L"Export Table",
    L"导出错误", L"Export errors",
    L"尚未连接数据库 — 双击左侧连接节点,或点「新建连接」", L"Not connected to a database — double-click a connection on the left, or click \\\"New Connection\\\"",
    L"工具", L"Tools",
    L"已停止", L"Stopped",
    L"已写入 %ld 行", L"%ld rows written",
    L"已删除 %d/%zu 张表", L"Deleted %d/%zu tables",
    L"已删除数据库", L"Database deleted",
    L"已删除表", L"Table deleted",
    L"已复制 CREATE 语句", L"CREATE statement copied",
    L"已复制表", L"Table copied",
    L"已复制表名", L"Table name copied",
    L"已导出表", L"Table exported",
    L"已执行 SQL 脚本", L"SQL script executed",
    L"已新建数据库", L"Database created",
    L"已更新数据库字符集", L"Database charset updated",
    L"已清空表", L"Table truncated",
    L"已粘贴表", L"Table pasted",
    L"已转储", L"Dumped",
    L"已重命名表", L"Table renamed",
    L"已重命名", L"Renamed",
    L"该数据库暂不支持此类对象重命名", L"This database does not support renaming this kind of object yet",
    L"读取对象定义失败:", L"Failed to read the object definition: ",
    L"新对象已创建，但删除旧对象失败:", L"The new object was created, but dropping the old one failed: ",
    L"帮助", L"Help",
    L"常规", L"General",
    L"应用名", L"Application Name",
    L"开发中", L"In Development",
    L"开始", L"Start",
    L"开始你的查询", L"Start Your Query",
    L"引擎", L"Engine",
    L"当前数据库无可修改的表选项", L"This database has no alterable table options",
    L"当前结果有 %d 行。此结果不是单表浏览，只能在界面线程一次性完成客户端排序，期间界面可能短暂无响应。是否继续？", L"The current result has %d rows. This isn't a single-table browse, so client-side sorting runs at once on the UI thread and the interface may briefly become unresponsive. Continue?",
    L"总体积", L"Total Size",
    L"总览", L"Overview",
    L"总览标签不可关闭", L"The Overview tab can't be closed",
    L"总览标签，不可关闭", L"Overview tab — can't be closed",
    L"成功 %d    失败 %d", L"OK %d    Failed %d",
    L"打印数据库", L"Print Database",
    L"打开日志文件夹", L"Open Log Folder",
    L"执行 SQL 文件", L"Run SQL File",
    L"执行 SQL 脚本", L"Run SQL Script",
    L"执行失败:\n\n", L"Execution failed:\n\n",
    L"执行完成", L"Execution complete",
    L"执行完成（有失败）", L"Execution complete (with failures)",
    L"技术详情", L"Technical Details",
    L"排序规则", L"Collation",
    L"排序较大的结果集", L"Sort a large result set",
    L"控制台", L"Console",
    L"插入字段", L"Insert Field",
    L"搜索", L"Search",
    L"搜索表名", L"Search table names",
    L"收藏", L"Favourites",
    L"放弃未保存的结构改动?", L"Discard unsaved structure changes?",
    L"数据库", L"Database",
    L"数据库信息", L"Database Info",
    L"数据库列表", L"Database List",
    L"数据库名单", L"Database Names",
    L"数据库名称", L"Database Name",
    L"数据库文件", L"Database File",
    L"数据空闲", L"Data Free",
    L"数据长度", L"Data Length",
    L"文件", L"File",
    L"文件中没有可执行的 SQL 语句。", L"The file contains no executable SQL statements.",
    L"文件编码", L"File Encoding",
    L"断线自动重连", L"Auto-reconnect on disconnect",
    L"新建表", L"New Table",
    L"新建表: ", L"New Table: ",
    L"新建连接 — ", L"New Connection — ",
    L"无", L"None",
    L"无可执行语句", L"No executable statements",
    L"无法写入文件:", L"Cannot write file: ",
    L"无法创建临时文件。", L"Cannot create a temporary file.",
    L"无法打开文件", L"Cannot open file",
    L"日志", L"Log",
    L"日志: ", L"Log: ",
    L"是", L"Yes",
    L"显示系统库(information_schema/mysql/pg_catalog…)", L"Show system databases (information_schema/mysql/pg_catalog…)",
    L"普通", L"Normal",
    L"更多工具", L"More Tools",
    L"最低 TLS 版本", L"Minimum TLS Version",
    L"最大数据长度", L"Max Data Length",
    L"未命名", L"Untitled",
    L"未命名连接", L"Untitled Connection",
    L"未连接", L"Not connected",
    L"未选择数据库", L"No database selected",
    L"本地绑定端口(0=自动)", L"Local bind port (0 = auto)",
    L"查看", L"View",
    L"查询失败", L"Query failed",
    L"检查时间", L"Check Time",
    L"正在加载表信息…", L"Loading table info…",
    L"正在导出函数 / 存储过程…", L"Exporting functions / stored procedures…",
    L"正在导出表  %d / %d ： %s", L"Exporting table  %d / %d : %s",
    L"正在导出视图…", L"Exporting views…",
    L"正在导出触发器…", L"Exporting triggers…",
    L"正在执行…", L"Running…",
    L"正在执行查询…", L"Running query…",
    L"正在转储…", L"Dumping…",
    L"此操作不可恢复。", L"This action cannot be undone.",
    L"没有可执行的语句", L"No executable statements",
    L"没有待保存的修改", L"No changes to save",
    L"没有检测到任何结构变更", L"No structure changes detected",
    L"没有检测到可新增的外键（既有外键为只读）", L"No new foreign keys detected (existing foreign keys are read-only)",
    L"没有检测到可新增的触发器", L"No new triggers detected",
    L"没有检测到索引变更", L"No index changes detected",
    L"注:连接时自动建立 SSH 隧道(支持密码 / 公钥 / 密码+公钥认证)。", L"Note: the SSH tunnel is established automatically on connect (password / public key / password+key auth supported).",
    L"注:隧道配置将被保存;隧道转发功能规划中。", L"Note: tunnel settings are saved; tunnel forwarding is planned.",
    L"注释", L"Comment",
    L"测试连接", L"Test Connection",
    L"清空表", L"Truncate Table",
    L"清空表失败:", L"Failed to truncate table: ",
    L"清除颜色", L"Clear Colour",
    L"源库与目标库引擎不同，表结构语句可能不兼容。仍要继续?", L"The source and target engines differ; the structure statements may be incompatible. Continue anyway?",
    L"源连接已关闭，剪贴板中的表不可用。", L"The source connection is closed; the copied table is unavailable.",
    L"版本", L"Version",
    L"用户名", L"Username",
    L"的所有数据?", L"?",
    L"目标数据库已存在同名表，请输入新表名:", L"A table with this name already exists in the target database; enter a new table name:",
    L"确定关闭该表设计？", L"Close this table design?",
    L"确定删除数据库?此操作不可恢复。", L"Delete this database? This action cannot be undone.",
    L"确定删除表", L"Delete table",
    L"确定删除表 ", L"Delete table ",
    L"确定删除选中的 %zu 张表？此操作不可恢复。", L"Delete the %zu selected tables? This action cannot be undone.",
    L"确定清空表", L"Truncate all data in table",
    L"确认保存", L"Confirm Save",
    L"确认创建表 ", L"Create table ",
    L"确认将当前修改保存到数据库?", L"Save the current changes to the database?",
    L"私钥密码短语", L"Private Key Passphrase",
    L"私钥文件", L"Private Key File",
    L"私钥文件路径", L"Private key file path",
    L"程序遇到一个问题", L"The application ran into a problem",
    L"程序遇到了一个严重错误，需要关闭。\n诊断信息已经保存下来，方便定位问题。", L"The application hit a fatal error and needs to close.\nDiagnostics have been saved to help pinpoint the issue.",
    L"窗口", L"Window",
    L"端口", L"Port",
    L"第 %d 行:字段 / 引用表 / 引用字段不能为空", L"Row %d: columns / referenced table / referenced columns can't be empty",
    L"第 %d 行:字段名和类型不能为空", L"Row %d: field name and type can't be empty",
    L"第 %d 行:本表字段数与引用字段数需一致", L"Row %d: the number of local columns must match the referenced columns",
    L"第 %d 行:索引名和字段不能为空", L"Row %d: index name and columns can't be empty",
    L"第 %d 行:触发器名 / 时机 / 事件 / 主体不能为空", L"Row %d: trigger name / timing / event / body can't be empty",
    L"粘贴表", L"Paste Table",
    L"索引长度", L"Index Length",
    L"结构变更", L"Structure Change",
    L"结构和数据", L"Structure & Data",
    L"继续使用", L"Keep Using",
    L"继续排序", L"Continue Sorting",
    L"编辑", L"Edit",
    L"编辑数据库", L"Edit Database",
    L"编辑数据库失败:", L"Failed to edit database: ",
    L"编辑连接 — ", L"Edit Connection — ",
    L"网格视图", L"Grid View",
    L"美化", L"Beautify",
    L"脚本文件", L"Script File",
    L"自动检测", L"Auto-detect",
    L"自增", L"Auto Increment",
    L"自定义", L"Custom",
    L"自定义颜色", L"Custom Colour",
    L"行数", L"Rows",
    L"行格式", L"Row Format",
    L"表信息", L"Table Info",
    L"表单", L"Form",
    L"表单视图", L"Form View",
    L"表名", L"Table Name",
    L"表名不能为空。", L"Table name can't be empty.",
    L"表数量", L"Tables",
    L"表注释", L"Table Comment",
    L"表结构已修改，是否保存更改？\n\n「是」保存并关闭     「否」放弃更改并关闭     「取消」不关闭", L"The table structure has changed. Save the changes?\n\n\\\"Yes\\\" save and close     \\\"No\\\" discard and close     \\\"Cancel\\\" keep open",
    L"表选项", L"Table Options",
    L"解释", L"Explain",
    L"触发器", L"Triggers",
    L"触发器主体", L"Trigger Body",
    L"认证方式", L"Authentication",
    L"设置颜色", L"Set Colour",
    L"设计: ", L"Design: ",
    L"设计表", L"Design Table",
    L"诊断日志：", L"Diagnostics log: ",
    L"该引擎暂不支持高级建库选项。", L"This engine doesn't support advanced database-creation options yet.",
    L"该数据库引擎不支持在创建后修改数据库字符集。", L"This database engine doesn't support changing a database's charset after creation.",
    L"该数据库没有可导出的表。", L"This database has no tables to export.",
    L"该页的保存将在后续版本实现。", L"Saving this tab will be implemented in a future version.",
    L"语句", L"Statement",
    L"请先在“字段”页添加至少一个字段。", L"Add at least one field on the \\\"Fields\\\" tab first.",
    L"请先在列表中选择一张表", L"Select a table in the list first",
    L"请先在列表中选择要删除的表", L"Select the tables to delete in the list first",
    L"请先选择一个数据库", L"Select a database first",
    L"请先选择一个数据库再打开 ER 图", L"Select a database before opening the ER diagram",
    L"请先选择一张表", L"Select a table first",
    L"请先选择一张表再打开表设计", L"Select a table before opening the table design",
    L"请输入表名：", L"Enter a table name:",
    L"读写超时(秒,0=无)", L"Read/write timeout (s, 0 = none)",
    L"读取文件失败", L"Failed to read file",
    L"读取源表结构失败:", L"Failed to read source table structure: ",
    L"读取结构失败 — ", L"Failed to read structure — ",
    L"读取结构失败:", L"Failed to read structure: ",
    L"读取表信息失败:", L"Failed to read table info: ",
    L"读取表失败:", L"Failed to read tables: ",
    L"读取表结构失败:", L"Failed to read table structure: ",
    L"转储 SQL 文件", L"Dump SQL File",
    L"转储失败", L"Dump failed",
    L"转储完成", L"Dump complete",
    L"转储结束", L"Dump finished",
    L"输入新表名:", L"Enter a new table name:",
    L"输入新名称:", L"Enter a new name:",
    L"运行", L"Run",
    L"返回", L"Back",
    L"连接信息", L"Connection Info",
    L"连接名", L"Connection Name",
    L"连接后执行的 SQL,用 ; 分隔", L"SQL to run after connecting, separated by ;",
    L"连接数据库并选择库后,此处显示 ER 关系图", L"Connect to a database and select one to show the ER diagram here",
    L"连接超时(秒)", L"Connect timeout (s)",
    L"逆向数据库到模型", L"Reverse Database to Model",
    L"选择 .db / .sqlite 文件", L"Choose a .db / .sqlite file",
    L"选择 SQL 脚本文件", L"Choose SQL script file",
    L"选择 SQLite 数据库文件", L"Choose SQLite database file",
    L"选择一个字段以编辑其方言属性", L"Select a field to edit its dialect-specific properties",
    L"选择字段", L"Select fields",
    L"选择左侧表以查看结构", L"Select a table on the left to view its structure",
    L"逗号分隔,如 shop_production, analytics", L"Comma-separated, e.g. shop_production, analytics",
    L"遇到错误继续执行（记录失败，不中断）", L"Continue on error (log failures, don't stop)",
    L"重命名", L"Rename",
    L"重命名失败:", L"Rename failed: ",
    L"鉴权", L"Authentication",
    L"鉴权密码", L"Auth Password",
    L"鉴权用户", L"Auth User",
    L"错误", L"Error",
    L"隔离级别", L"Isolation Level",
    L"隧道 URL", L"Tunnel URL",
    L"隧道 keepalive(秒)", L"Tunnel keepalive (s)",
    L"隧道压缩", L"Tunnel compression",
    L"验证服务器主机名", L"Verify server hostname",
    L"验证服务器证书", L"Verify server certificate",
    L"验证服务器证书(https)", L"Verify server certificate (https)",
    L"高级", L"Advanced",
    L"默认", L"Default",
    L"默认 schema", L"Default schema",
    L"默认值", L"Default Value",
    L"（图片预览：", L"(Image preview: ",
    L"（当前内容不是可识别的图片数据）", L"(The current content isn't recognizable image data)",
    L"（请选择一行）", L"(Select a row)",
    L"？此操作不可恢复。", L"? This action cannot be undone.",
    L"红色", L"Red",
    L"橙色", L"Orange",
    L"黄色", L"Yellow",
    L"绿色", L"Green",
    L"蓝色", L"Blue",
    L"紫色", L"Purple",
    L"灰色", L"Grey",

    // ---- i18n coverage top-up (round 2): tr(var) pool literals (headers/tabs/toolbar) ----
    L"DDL 预览", L"DDL Preview",
    L"上移当前字段", L"Move current field up",
    L"上移触发器", L"Move trigger up",
    L"下移当前字段", L"Move current field down",
    L"下移触发器", L"Move trigger down",
    L"仅密钥", L"Key only",
    L"仅显示以下", L"Show only these",
    L"保存该页变更", L"Save changes on this tab",
    L"公钥", L"Public key",
    L"删除", L"Delete",
    L"确定删除", L"Delete",
    L"打开视图", L"Open View",
    L"修改视图", L"Modify View",
    L"新建视图", L"New View",
    L"复制视图名", L"Copy View Name",
    L"删除视图", L"Delete View",
    L"删除函数", L"Delete Function",
    L"删除存储过程", L"Delete Procedure",
    L"删除包", L"Delete Package",
    L"删除当前字段", L"Delete current field",
    L"删除时", L"On Delete",
    L"删除选中外键", L"Delete selected foreign key",
    L"删除选中索引", L"Delete selected index",
    L"删除选中触发器", L"Delete selected trigger",
    L"名称", L"Name",
    L"在当前字段上方插入", L"Insert above the current field",
    L"在末尾追加字段", L"Append a field at the end",
    L"外键", L"Foreign Keys",
    L"字段名", L"Field Name",
    L"密码 + 公钥", L"Password + public key",
    L"密钥 + 密码短语", L"Key + passphrase",
    L"序号", L"No.",
    L"时机", L"Timing",
    L"事件", L"Event",
    L"引用字段", L"Referenced Column",
    L"引用库", L"Referenced Database",
    L"引用表", L"Referenced Table",
    L"排除以下", L"Exclude these",
    L"数据库默认", L"Database default",
    L"新增", L"Add",
    L"新增外键", L"Add Foreign Key",
    L"新增索引", L"Add Index",
    L"新增触发器", L"Add Trigger",
    L"方式", L"Method",
    L"无客户端认证", L"No client authentication",
    L"显示全部", L"Show all",
    L"更新时", L"On Update",
    L"步骤 1 / 5 · 源与目标", L"Step 1 / 5 · Source & Target",
    L"步骤 2 / 5 · 同步内容", L"Step 2 / 5 · What to Sync",
    L"步骤 3 / 5 · 正在比对", L"Step 3 / 5 · Comparing",
    L"步骤 4 / 5 · 差异审阅", L"Step 4 / 5 · Review Differences",
    L"步骤 5 / 5 · SQL 预览", L"Step 5 / 5 · SQL Preview",
    L"类型", L"Type",
    L"精度", L"Scale",
    L"索引", L"Indexes",
    L"索引名", L"Index Name",
    L"虚拟", L"Virtual",
    L"设为/取消主键", L"Set/unset primary key",
    L"选项", L"Options",
    // table-option labels (db-layer DbCreateOption.label, rendered via tr in 选项 tab)
    L"引擎", L"Engine",
    L"行格式", L"Row Format",
    L"最大行数", L"Max Rows",
    L"自增起始", L"Auto-Increment Start",
    L"平均行长", L"Avg Row Length",
    L"校验和", L"Checksum",
    L"键", L"Key",
    L"长度", L"Length",
    L"非空", L"Not Null",

    // ---- i18n coverage top-up (round 3): result panel + file-dialog filters ----
    L"结果", L"Results",
    L"消息", L"Messages",
    L"● 正在执行查询…", L"● Running query…",
    L"\n⚠ 结果较大：表格仅显示前 %llu 行（共 %llu 行）。请加 LIMIT 或导出查看全部。", L"\n⚠ Result is large: showing only the first %llu of %llu rows. Add LIMIT or export to see all.",
    L"● %llu rows（仅显示前 %llu）   %ld ms   |   %s", L"● %llu rows (showing first %llu)   %ld ms   |   %s",
    L"● 查询失败(详见消息页)", L"● Query failed (see Messages tab)",
    L"● 查询失败", L"● Query failed",
    L"SQL 文件 (*.sql)|*.sql|所有文件 (*.*)|*.*", L"SQL Files (*.sql)|*.sql|All Files (*.*)|*.*",
    L"文本文件 (*.txt)|*.txt|所有文件 (*.*)|*.*", L"Text Files (*.txt)|*.txt|All Files (*.*)|*.*",
    L"数据文件 (*.csv;*.txt;*.json;*.xml;*.sql)|*.csv;*.txt;*.json;*.xml;*.sql|所有文件 (*.*)|*.*", L"Data Files (*.csv;*.txt;*.json;*.xml;*.sql)|*.csv;*.txt;*.json;*.xml;*.sql|All Files (*.*)|*.*",

    // ---- i18n coverage top-up (round 4): db-layer labels rendered in the UI ----
    // AttrDescriptor.label (字段属性面板, rendered via tr in BuildAttrPanel)
    L"无符号", L"Unsigned",
    L"BINARY", L"BINARY",
    L"索引前缀长度", L"Index Prefix Length",
    L"生成列", L"Generated",
    L"计算列", L"Computed Column",
    L"标识(IDENTITY)", L"Identity (IDENTITY)",
    L"标识/自增", L"Identity / Auto Increment",
    // GetDatabaseOverview column labels (数据库列表 grid, rendered via tr)
    L"表数", L"Tables",
    L"所有者", L"Owner",
    L"恢复模式", L"Recovery Model",
    L"文件路径", L"File Path",

    // ---- object editors: save status / routine execute / compile ----
    L"保存成功", L"Saved successfully",
    L"执行存储过程", L"Execute Procedure",
    L"执行函数", L"Execute Function",
    L"按顺序填写每个参数(参数名仅供参考);留空的值按 NULL 传入。",
        L"Fill in each parameter in order (the name is for reference only); a blank value is passed as NULL.",
    L"参数名", L"Parameter",
    L"值", L"Value",
    L"数字", L"Number",
    L"小数", L"Decimal",
    L"集合(SET/ARRAY)", L"Set (SET/ARRAY)",
    L"添加参数", L"Add Parameter",
    L"删除参数", L"Delete Parameter",
    L"编译", L"Compile",
    L"编译错误", L"Compile Error",
    L"%s 编译成功", L"%s compiled successfully",
    // object-editor top connection/database selector bar
    L"连接:",       L"Connection: ",
    L"数据库:",     L"Database: ",
    L"请选择连接",   L"Select a connection",
    L"连接已断开",   L"Connection has been disconnected",

    // ---- saved-SQL script library ----
    L"脚本库",       L"Script Library",
    L"SQL脚本",      L"SQL Scripts",
    L"打开",         L"Open",
    L"文件大小",     L"File Size",
    L"归属用户",     L"Owner",
    L"执行用户",     L"Executed By",
    L"保存 SQL 脚本", L"Save SQL Script",
    L"脚本名称:",     L"Script name:",
    L"删除脚本",     L"Delete Script",
    L"打开脚本",     L"Open Script",
    L"确定删除脚本「%s」吗?此操作不可撤销。",
        L"Delete the script \"%s\"? This cannot be undone.",
    L"脚本「%s」已存在，覆盖它吗?",
        L"A script named \"%s\" already exists. Overwrite it?",
    L"已保存脚本: %s", L"Script saved: %s",

    // ---- visual query builder ----
    L"构建查询",     L"Build Query",
    L"构建查询: ",   L"Build Query: ",
    L"请先连接并选择数据库,再构建查询。",
        L"Connect and pick a database first, then build a query.",
    L"请先选择一个数据库(在左侧展开并点击一个库)。",
        L"Pick a database first (expand a connection on the left and click a database).",
    L"搜索表…",       L"Search tables…",
    L"双击添加到画布", L"Double-click to add to canvas",
    L"%zu 张表 · 双击添加", L"%zu tables · double-click to add",
    L"双击左侧表名,把表添加到画布",
        L"Double-click a table on the left to add it to the canvas",
    L"勾选列 → SELECT · 点一列再点另一表的列 → 建立 JOIN",
        L"Check a column → SELECT · click one column then another table's column → JOIN",
    L"SQL 预览",     L"SQL Preview",
    L"清空画布",     L"Clear Canvas",
    L"复制 SQL",     L"Copy SQL",
    L"应用到编辑器", L"Apply to Editor",
    L"删除连接",     L"Delete Join",
    L"画布上还没有表,先从左侧添加一张表。",
        L"No tables on the canvas yet — add one from the left first.",
    L"连接已断开。",  L"The connection has been closed.",
    L"读取表失败",   L"Failed to read tables",
    L"读取表列表失败:", L"Failed to read the table list: ",
    L"读取列失败:",   L"Failed to read columns: ",
    L"-- 添加表并勾选列后,这里会实时生成 SELECT 语句",
        L"-- Add tables and check columns; the SELECT statement is generated here live",
    L"未勾选任何列,默认 SELECT *(勾选列以精确选择字段)",
        L"No columns checked — defaulting to SELECT * (check columns to pick exact fields)",

    // ---- object-list tabs (表 / 视图 / 函数 / 存储过程 toolbar) ----
    L"大小", L"Size",
    L"修改函数", L"Modify Function",
    L"修改存储过程", L"Modify Procedure",
    L"新增函数", L"New Function",
    L"新增存储过程", L"New Procedure",
    L"筛选…", L"Filter…",
    L"对象列表", L"Object List",
    L"读取对象列表失败:", L"Failed to read the object list: ",
    L"请先连接并打开一个数据库。", L"Connect and open a database first.",

    // ---- user / privilege management (用户组) ----
    L"用户组", L"Users",
    L"用户管理", L"User Management",
    L"用户: ", L"Users: ",
    L"用户 (User@Host)", L"User (User@Host)",
    L"认证插件", L"Auth Plugin",
    L"请先连接一个数据库。", L"Connect to a database first.",
    L"当前数据库暂不支持用户管理。", L"User management is not supported for this database yet.",
    L"新用户", L"New User",
    L"编辑用户", L"Edit User",
    L"删除用户", L"Delete User",
    L"复制", L"Duplicate",
    L"刷新", L"Refresh",
    L"确定删除选中的 %zu 个用户?此操作不可撤销。",
        L"Delete the %zu selected user(s)? This cannot be undone.",
    L"删除失败: ", L"Delete failed: ",
    L"复制用户", L"Duplicate User",
    L"新用户名 (主机沿用 ", L"New user name (host stays ",
    L"新建用户", L"New User",
    L"编辑用户: ", L"Edit User: ",
    L"保存", L"Save",
    L"取消", L"Cancel",
    L"常规", L"General",
    L"隶属成员", L"Member Of",
    L"成员", L"Members",
    L"服务器权限", L"Server Privileges",
    L"数据库权限", L"Database Privileges",
    L"高级", L"Advanced",
    L"用户名", L"User Name",
    L"主机", L"Host",
    L"密码", L"Password",
    L"修改密码", L"Change password",
    L"(服务器默认)", L"(server default)",
    L"提示: 主机 % 表示允许任意来源;编辑已有用户时不可改用户名/主机(重命名为独立操作)。",
        L"Tip: host % allows any origin; user name/host are read-only when editing (rename is a separate op).",
    L"全局权限 (*.*) — 作用于服务器上所有数据库:",
        L"Global privileges (*.*) — apply to every database on the server:",
    L"数据库", L"Database",
    L"该库权限 (db.*)", L"Privileges on this database (db.*)",
    L"隶属成员 — 勾选授予本账户的角色 (MySQL 8;5.7 忽略):",
        L"Member Of — check roles granted to this account (MySQL 8; ignored on 5.7):",
    L"成员 — 将本账户当作角色持有的用户 (只读):",
        L"Members — accounts that hold this one as a role (read-only):",
    L"设置资源限制 (WITH MAX_…)", L"Set resource limits (WITH MAX_…)",
    L"每小时最大查询数 (0=无限)", L"Max queries per hour (0 = unlimited)",
    L"每小时最大更新数 (0=无限)", L"Max updates per hour (0 = unlimited)",
    L"每小时最大连接数 (0=无限)", L"Max connections per hour (0 = unlimited)",
    L"最大并发连接数 (0=无限)", L"Max concurrent connections (0 = unlimited)",
    L"要求 SSL 连接 (REQUIRE SSL)", L"Require SSL connection (REQUIRE SSL)",
    L"提示: 未勾选\"设置资源限制\"时不改动这些项;已有限制不会回填显示。",
        L"Tip: these are left unchanged unless \"Set resource limits\" is ticked; existing limits are not back-filled.",
    L"请填写用户名。", L"Please enter a user name.",
    L"保存用户失败:", L"Failed to save user: ",

    nullptr
};

} // namespace core
